// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UEnumTable.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cmd {

  /// <summary>Holder for reflection information generated from UEnumTable.proto</summary>
  public static partial class UEnumTableReflection {

    #region Descriptor
    /// <summary>File descriptor for UEnumTable.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UEnumTableReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBVRW51bVRhYmxlLnByb3RvEgNDbWQqXwobRVNjZW5lT2JqZWN0SW50ZXJh",
            "Y3Rpb25Nb2RlEggKBE5vbmUQABIJCgVWaXNpdBABEgoKBkF0dGFjaxACEgsK",
            "B092ZXJsYXAQAxISCg5WaXNpdEFuZEF0dGFjaxAEKnUKGkVTT0JDRXZlbnRS",
            "ZXNwb25zZUhhbmRsaW5nEgsKB0RlZmF1bHQQABIMCghPbmVCeU9uZRABEhEK",
            "DUNsZWFyUHJldmlvdXMQAhIPCgtBYmFuZG9uTmV4dBADEhgKFEFiYW5kb25T",
            "YW1lRXZlbnROZXh0EAQq6wIKEEVTdGFnZU9iamVjdFR5cGUSDgoKRVNPVFBs",
            "YXllchAAEhEKDUVTT1ROZXRQbGF5ZXIQARIPCgtFU09UUGFydG5lchACEgsK",
            "B0VTT1ROcGMQAxIVChFFU09UTm9ybWFsTW9uc3RlchAEEhYKEkVTT1RQYXJ0",
            "bmVyTW9uc3RlchAFEhUKEUVTT1RFbGl0ZXNNb25zdGVyEAYSEwoPRVNPVEJv",
            "c3NNb25zdGVyEAcSEwoPRVNPVEJvc3NBbmNpZW50EAgSEgoORVNPVE5vcm1h",
            "bEl0ZW0QCRISCg5FU09UUmVwYWlySXRlbRAKEhMKD0VTT1RDb2xsZWN0SXRl",
            "bRALEg8KC0VTT1RCb3hJdGVtEAwSEgoORVNPVEJhdHRsZUl0ZW0QDRIPCgtF",
            "U09UVG95SXRlbRAOEg8KC0VTT1RWZWhpY2xlEA8SEAoMRVNPVERyb3BJdGVt",
            "EBASEAoMRVNPVE1hcEFjdG9yEBEqfwoSRUNoYXJhY3RlcmlzdGljVGFnEgwK",
            "CEVDVF9DdXRlEAASDAoIRUNUX1NleHkQARIMCghFQ1RfQ29vbBACEgsKB0VD",
            "VF9TaHkQAxIPCgtFQ1RfRWxlZ2FudBAEEhAKDEVDVF9Jbm5vY2VudBAFEg8K",
            "C0VDVF9EeW5hbWljEAYqPwoNRUF2YXRhclNvY2tldBILCgdFQVNCb2R5EAAS",
            "DwoLRUFTTGVmdEhhbmQQARIQCgxFQVNSaWdodEhhbmQQAip/ChFFQWN0aXZl",
            "RGF0aW5nRm9ybRINCglIb3RTcHJpbmcQABILCgdSZWFkaW5nEAESCQoFU3dp",
            "bmcQAhILCgdXYWxraW5nEAMSCwoHQ2FtcGluZxAEEgwKCFJlc2VhcmNoEAUS",
            "CgoGUGV0Q2F0EAYSDwoLTG9va2luZ1N0YXIQByrzAQoSRUFjdGl2ZURhdGlu",
            "Z1RvcGljEgcKA0NhdBAAEggKBEZvb2QQARIJCgVTdHVkeRACEg0KCVNvY2ll",
            "dGllcxADEgwKCEludGVyZXN0EAQSEAoMUmVsYXRpb25zaGlwEAUSCAoEUGFz",
            "dBAGEggKBEhvbWUQBxIJCgVEcmVhbRAIEgwKCE1lZGljaW5lEAkSCAoETGlm",
            "ZRAKEgoKBkZpZ3VyZRALEgkKBUhhYml0EAwSCQoFRmFpdGgQDRIHCgNKb2IQ",
            "DhIJCgVTa2lsbBAPEgkKBUxpa2VzEBASCQoFSG9iYnkQERINCglTdHJlbmd0",
            "aHMQEipECg1FQW5pbUJlaGF2aW9yEhUKEUFuaW1CZWhhdmlvcl9Ob25lEAAS",
            "HAoYQW5pbUJlaGF2aW9yX0VudGVyQ29tYmF0EAEqSAoMRURlc3Ryb3lUeXBl",
            "EgoKBk5vcm1hbBAAEgsKB0ZhZGVvdXQQARIRCg1EaXJlY3REZXN0cm95EAIS",
            "DAoIRWRpdFRlYW0QAypRCgtFRmlsdGVyVHlwZRISCg5GaWx0ZXJUeXBlTm9u",
            "ZRAAEgsKB0NvcnJ1cHQQARIKCgZNZW1vcnkQAhIJCgVEZWF0aBADEgoKBlNl",
            "YXJjaBAEKigKE0VOZXRQZXJmb3JtYW5jZVR5cGUSEQoNUGxheUFuaW1hdGlv",
            "bhAAKjUKEkVCYXR0bGVJdGVtU3ViVHlwZRIICgREcm9wEAASCAoEVHJhcBAB",
            "EgsKB1RyaWdnZXIQAio+ChFFU09CZWhhdmlvclRhcmdldBIKCgZPYmplY3QQ",
            "ABIMCghPcGVyYXRvchABEg8KC09iamVjdE93bmVyEAIqUwoWRVNPQmVoYXZp",
            "b3JDb250cm9sVHlwZRINCglTT0JDVE5vbmUQABIJCgVTdGFydBABEggKBFN0",
            "b3AQAhIJCgVQYXVzZRADEgoKBlJlc3VtZRAEKkIKHEVTT0JlaGF2aW9ySW50",
            "ZXJydXB0SGFuZGxpbmcSDQoJU09CSUhOb25lEAASCAoER29PbhABEgkKBUJy",
            "ZWFrEAJCB1oFLjtDbWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cmd.ESceneObjectInteractionMode), typeof(global::Cmd.ESOBCEventResponseHandling), typeof(global::Cmd.EStageObjectType), typeof(global::Cmd.ECharacteristicTag), typeof(global::Cmd.EAvatarSocket), typeof(global::Cmd.EActiveDatingForm), typeof(global::Cmd.EActiveDatingTopic), typeof(global::Cmd.EAnimBehavior), typeof(global::Cmd.EDestroyType), typeof(global::Cmd.EFilterType), typeof(global::Cmd.ENetPerformanceType), typeof(global::Cmd.EBattleItemSubType), typeof(global::Cmd.ESOBehaviorTarget), typeof(global::Cmd.ESOBehaviorControlType), typeof(global::Cmd.ESOBehaviorInterruptHandling), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ESceneObjectInteractionMode {
    /// <summary>
    /// 无法访问
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    /// 访问（对象带阻挡）
    /// </summary>
    [pbr::OriginalName("Visit")] Visit = 1,
    /// <summary>
    /// 仅允许被攻击
    /// </summary>
    [pbr::OriginalName("Attack")] Attack = 2,
    /// <summary>
    /// 访问（对象不带阻挡）
    /// </summary>
    [pbr::OriginalName("Overlap")] Overlap = 3,
    /// <summary>
    /// 允许访问并且允许被攻击（禁止使用）
    /// </summary>
    [pbr::OriginalName("VisitAndAttack")] VisitAndAttack = 4,
  }

  public enum ESOBCEventResponseHandling {
    /// <summary>
    /// 默认处理规则，当前为OneByOne
    /// </summary>
    [pbr::OriginalName("Default")] Default = 0,
    /// <summary>
    /// 一个接一个的排队响应处理
    /// </summary>
    [pbr::OriginalName("OneByOne")] OneByOne = 1,
    /// <summary>
    /// 清除前面正在执行和待执行的事件，并响应新的事件
    /// </summary>
    [pbr::OriginalName("ClearPrevious")] ClearPrevious = 2,
    /// <summary>
    /// 如果前面正在响应处理，则抛弃新的事件
    /// </summary>
    [pbr::OriginalName("AbandonNext")] AbandonNext = 3,
    /// <summary>
    /// 如果前面正在响应处理或已缓存相同的事件，则抛弃新的事件
    /// </summary>
    [pbr::OriginalName("AbandonSameEventNext")] AbandonSameEventNext = 4,
  }

  public enum EStageObjectType {
    /// <summary>
    /// 玩家
    /// </summary>
    [pbr::OriginalName("ESOTPlayer")] Esotplayer = 0,
    /// <summary>
    /// 网络上其他玩家
    /// </summary>
    [pbr::OriginalName("ESOTNetPlayer")] EsotnetPlayer = 1,
    /// <summary>
    /// 伙伴
    /// </summary>
    [pbr::OriginalName("ESOTPartner")] Esotpartner = 2,
    /// <summary>
    /// NPC
    /// </summary>
    [pbr::OriginalName("ESOTNpc")] Esotnpc = 3,
    /// <summary>
    /// 普通魔物
    /// </summary>
    [pbr::OriginalName("ESOTNormalMonster")] EsotnormalMonster = 4,
    /// <summary>
    /// 伙伴魔物
    /// </summary>
    [pbr::OriginalName("ESOTPartnerMonster")] EsotpartnerMonster = 5,
    /// <summary>
    /// 精英魔物
    /// </summary>
    [pbr::OriginalName("ESOTElitesMonster")] EsotelitesMonster = 6,
    /// <summary>
    /// Boss魔物
    /// </summary>
    [pbr::OriginalName("ESOTBossMonster")] EsotbossMonster = 7,
    /// <summary>
    /// Boss古神
    /// </summary>
    [pbr::OriginalName("ESOTBossAncient")] EsotbossAncient = 8,
    /// <summary>
    /// 场景物件
    /// </summary>
    [pbr::OriginalName("ESOTNormalItem")] EsotnormalItem = 9,
    /// <summary>
    /// 修复物
    /// </summary>
    [pbr::OriginalName("ESOTRepairItem")] EsotrepairItem = 10,
    /// <summary>
    /// 采集物
    /// </summary>
    [pbr::OriginalName("ESOTCollectItem")] EsotcollectItem = 11,
    /// <summary>
    /// 宝箱
    /// </summary>
    [pbr::OriginalName("ESOTBoxItem")] EsotboxItem = 12,
    /// <summary>
    /// 战斗道具
    /// </summary>
    [pbr::OriginalName("ESOTBattleItem")] EsotbattleItem = 13,
    /// <summary>
    /// 玩具
    /// </summary>
    [pbr::OriginalName("ESOTToyItem")] EsottoyItem = 14,
    /// <summary>
    /// 载具
    /// </summary>
    [pbr::OriginalName("ESOTVehicle")] Esotvehicle = 15,
    /// <summary>
    /// 掉落道具
    /// </summary>
    [pbr::OriginalName("ESOTDropItem")] EsotdropItem = 16,
    /// <summary>
    /// 地图烘培对象
    /// </summary>
    [pbr::OriginalName("ESOTMapActor")] EsotmapActor = 17,
  }

  public enum ECharacteristicTag {
    /// <summary>
    /// 可爱
    /// </summary>
    [pbr::OriginalName("ECT_Cute")] EctCute = 0,
    /// <summary>
    /// 性感
    /// </summary>
    [pbr::OriginalName("ECT_Sexy")] EctSexy = 1,
    /// <summary>
    /// 帅气
    /// </summary>
    [pbr::OriginalName("ECT_Cool")] EctCool = 2,
    /// <summary>
    /// 害羞
    /// </summary>
    [pbr::OriginalName("ECT_Shy")] EctShy = 3,
    /// <summary>
    /// 优雅
    /// </summary>
    [pbr::OriginalName("ECT_Elegant")] EctElegant = 4,
    /// <summary>
    /// 天然
    /// </summary>
    [pbr::OriginalName("ECT_Innocent")] EctInnocent = 5,
    /// <summary>
    /// 元气
    /// </summary>
    [pbr::OriginalName("ECT_Dynamic")] EctDynamic = 6,
  }

  public enum EAvatarSocket {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EASBody")] Easbody = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EASLeftHand")] EasleftHand = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EASRightHand")] EasrightHand = 2,
  }

  public enum EActiveDatingForm {
    /// <summary>
    /// 泡温泉
    /// </summary>
    [pbr::OriginalName("HotSpring")] HotSpring = 0,
    /// <summary>
    /// 看书自习
    /// </summary>
    [pbr::OriginalName("Reading")] Reading = 1,
    /// <summary>
    /// 荡秋千
    /// </summary>
    [pbr::OriginalName("Swing")] Swing = 2,
    /// <summary>
    /// 散步
    /// </summary>
    [pbr::OriginalName("Walking")] Walking = 3,
    /// <summary>
    /// 野餐
    /// </summary>
    [pbr::OriginalName("Camping")] Camping = 4,
    /// <summary>
    /// 调查研究
    /// </summary>
    [pbr::OriginalName("Research")] Research = 5,
    /// <summary>
    /// 撸猫
    /// </summary>
    [pbr::OriginalName("PetCat")] PetCat = 6,
    /// <summary>
    /// 看星星
    /// </summary>
    [pbr::OriginalName("LookingStar")] LookingStar = 7,
  }

  public enum EActiveDatingTopic {
    /// <summary>
    /// 猫
    /// </summary>
    [pbr::OriginalName("Cat")] Cat = 0,
    /// <summary>
    /// 美食
    /// </summary>
    [pbr::OriginalName("Food")] Food = 1,
    /// <summary>
    /// 学习
    /// </summary>
    [pbr::OriginalName("Study")] Study = 2,
    /// <summary>
    /// 社团
    /// </summary>
    [pbr::OriginalName("Societies")] Societies = 3,
    /// <summary>
    /// 兴趣
    /// </summary>
    [pbr::OriginalName("Interest")] Interest = 4,
    /// <summary>
    /// 关系
    /// </summary>
    [pbr::OriginalName("Relationship")] Relationship = 5,
    /// <summary>
    /// 过去
    /// </summary>
    [pbr::OriginalName("Past")] Past = 6,
    /// <summary>
    /// 故乡
    /// </summary>
    [pbr::OriginalName("Home")] Home = 7,
    /// <summary>
    /// 梦想
    /// </summary>
    [pbr::OriginalName("Dream")] Dream = 8,
    /// <summary>
    /// 药物
    /// </summary>
    [pbr::OriginalName("Medicine")] Medicine = 9,
    /// <summary>
    /// 生死
    /// </summary>
    [pbr::OriginalName("Life")] Life = 10,
    /// <summary>
    /// 身材
    /// </summary>
    [pbr::OriginalName("Figure")] Figure = 11,
    /// <summary>
    /// 习惯
    /// </summary>
    [pbr::OriginalName("Habit")] Habit = 12,
    /// <summary>
    /// 信念
    /// </summary>
    [pbr::OriginalName("Faith")] Faith = 13,
    /// <summary>
    /// 工作
    /// </summary>
    [pbr::OriginalName("Job")] Job = 14,
    /// <summary>
    /// 技能
    /// </summary>
    [pbr::OriginalName("Skill")] Skill = 15,
    /// <summary>
    /// 喜好
    /// </summary>
    [pbr::OriginalName("Likes")] Likes = 16,
    /// <summary>
    /// 癖好
    /// </summary>
    [pbr::OriginalName("Hobby")] Hobby = 17,
    /// <summary>
    /// 特长
    /// </summary>
    [pbr::OriginalName("Strengths")] Strengths = 18,
  }

  public enum EAnimBehavior {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("AnimBehavior_None")] AnimBehaviorNone = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("AnimBehavior_EnterCombat")] AnimBehaviorEnterCombat = 1,
  }

  public enum EDestroyType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Normal")] Normal = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Fadeout")] Fadeout = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("DirectDestroy")] DirectDestroy = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EditTeam")] EditTeam = 3,
  }

  public enum EFilterType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("FilterTypeNone")] FilterTypeNone = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Corrupt")] Corrupt = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Memory")] Memory = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Death")] Death = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Search")] Search = 4,
  }

  public enum ENetPerformanceType {
    /// <summary>
    /// 播放动画
    /// </summary>
    [pbr::OriginalName("PlayAnimation")] PlayAnimation = 0,
  }

  public enum EBattleItemSubType {
    /// <summary>
    /// 战斗道具掉落
    /// </summary>
    [pbr::OriginalName("Drop")] Drop = 0,
    /// <summary>
    /// 战斗陷阱
    /// </summary>
    [pbr::OriginalName("Trap")] Trap = 1,
    /// <summary>
    /// Overlap触发器
    /// </summary>
    [pbr::OriginalName("Trigger")] Trigger = 2,
  }

  public enum ESOBehaviorTarget {
    /// <summary>
    /// 被交互的对象，如场景物件
    /// </summary>
    [pbr::OriginalName("Object")] Object = 0,
    /// <summary>
    /// 交互的发起者，如玩家
    /// </summary>
    [pbr::OriginalName("Operator")] Operator = 1,
    /// <summary>
    /// 被交互的对象的所有者，如场景物件的拥有者
    /// </summary>
    [pbr::OriginalName("ObjectOwner")] ObjectOwner = 2,
  }

  public enum ESOBehaviorControlType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SOBCTNone")] Sobctnone = 0,
    /// <summary>
    /// 开始
    /// </summary>
    [pbr::OriginalName("Start")] Start = 1,
    /// <summary>
    /// 结束
    /// </summary>
    [pbr::OriginalName("Stop")] Stop = 2,
    /// <summary>
    /// 暂停
    /// </summary>
    [pbr::OriginalName("Pause")] Pause = 3,
    /// <summary>
    /// 继续
    /// </summary>
    [pbr::OriginalName("Resume")] Resume = 4,
  }

  public enum ESOBehaviorInterruptHandling {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SOBIHNone")] Sobihnone = 0,
    /// <summary>
    /// 继续
    /// </summary>
    [pbr::OriginalName("GoOn")] GoOn = 1,
    /// <summary>
    /// 打断、中止
    /// </summary>
    [pbr::OriginalName("Break")] Break = 2,
  }

  #endregion

}

#endregion Designer generated code
