// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoAttr.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cmd {

  /// <summary>Holder for reflection information generated from ProtoAttr.proto</summary>
  public static partial class ProtoAttrReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoAttr.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoAttrReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm90b0F0dHIucHJvdG8SA0NtZCr9BgoNRU5pbmVEYXRhVHlwZRIVChFF",
            "TklORURBVEFUWVBFX01JThAAEhgKFEVOSU5FREFUQVRZUEVfV0VBUE9OEAES",
            "FgoSRU5JTkVEQVRBVFlQRV9IRUFEEAISGgoWRU5JTkVEQVRBVFlQRV9FQVJS",
            "SU5HUxADEhYKEkVOSU5FREFUQVRZUEVfRkFDRRAEEhcKE0VOSU5FREFUQVRZ",
            "UEVfTU9VVEgQBRIWChJFTklORURBVEFUWVBFX0JBQ0sQBhIWChJFTklORURB",
            "VEFUWVBFX1RBSUwQBxIZChVFTklORURBVEFUWVBFX0ZBU0hJT04QCBIYChRF",
            "TklORURBVEFUWVBFX1NUQVRVUxAPEhwKGEVOSU5FREFUQVRZUEVfS0lMTEVS",
            "TkFNRRAQEiEKHUVOSU5FREFUQVRZUEVfTlBDX0lOVEVSQUNUSU9OEBESHQoZ",
            "RU5JTkVEQVRBVFlQRV9GSUdIVFNUQVRVUxAUEhwKGEVOSU5FREFUQVRZUEVf",
            "Q1VSX0xPQ0tJRBAVEhsKF0VOSU5FREFUQVRZUEVfRVFVSVBfSURTEBYSGQoV",
            "RU5JTkVEQVRBVFlQRV9DQU1QX0lEEBcSGwoXRU5JTkVEQVRBVFlQRV9ST0xF",
            "TEVWRUwQGBIZChVFTklORURBVEFUWVBFX1JPTEVFWFAQGRIaChZFTklORURB",
            "VEFUWVBFX0tJTExFUklEEBoSHAoYRU5JTkVEQVRBVFlQRV9TV09SRFNUQVRF",
            "EBsSIQodRU5JTkVEQVRBVFlQRV9QRVJTT05BTElUWURBVEEQHBIcChhFTklO",
            "RURBVEFUWVBFX0FOR0VSU1RBVEUQHRIgChxFTklORURBVEFUWVBFX0lETEVf",
            "U1VCU1RBVFVTEB4SGQoVRU5JTkVEQVRBVFlQRV9DQVRHVUlEEB8SHAoYRU5J",
            "TkVEQVRBVFlQRV9QQVNTRU5HRVJTECASGQoVRU5JTkVEQVRBVFlQRV9WRUhJ",
            "Q0xFECESIAocRU5JTkVEQVRBVFlQRV9XRUFQT05JTlRFUkFDVBAiEh8KG0VO",
            "SU5FREFUQVRZUEVfQkFSUklFUlNUQVRVUxAjEhsKF0VOSU5FREFUQVRZUEVf",
            "Qk9TU1NUQUdFECQSGwoXRU5JTkVEQVRBVFlQRV9DT01CQVRfSUQQJRIVChFF",
            "TklORURBVEFUWVBFX01BWBAmKrwCChFFSXRlbU5pbmVEYXRhVHlwZRIaChZF",
            "SVRFTV9OSU5FREFUQVRZUEVfTUlOEAASGgoWRUlURU1fTklORURBVEFUWVBF",
            "X0RJUhABEiIKHkVJVEVNX05JTkVEQVRBVFlQRV9JTlRFUkFDVElPThACEiEK",
            "HUVJVEVNX05JTkVEQVRBVFlQRV9QQVNTRU5HRVJTEAMSHgoaRUlURU1fTklO",
            "RURBVEFUWVBFX1ZFSElDTEUQBBIjCh9FSVRFTV9OSU5FREFUQVRZUEVfTU9E",
            "RUxfSEVJR0hUEAYSIgoeRUlURU1fTklORURBVEFUWVBFX01PREVMX1dJRFRI",
            "EAcSIwofRUlURU1fTklORURBVEFUWVBFX01PREVMX0xFTkdUSBAIEhoKFkVJ",
            "VEVNX05JTkVEQVRBVFlQRV9NQVgQCSqBKAoJRUF0dHJUeXBlEhEKDUVBVFRS",
            "VFlQRV9NSU4QABIRCg1FQVRUUlRZUEVfRVhQEAESEAoMRUFUVFJUWVBFX0xW",
            "EAISFQoRRUFUVFJUWVBFX1NUQVRVUzEQChIVChFFQVRUUlRZUEVfU1RBVFVT",
            "MhALEhUKEUVBVFRSVFlQRV9TVEFUVVMzEAwSFQoRRUFUVFJUWVBFX1NUQVRV",
            "UzQQDRIVChFFQVRUUlRZUEVfU1RBVFVTNRAOEhgKFEVBVFRSVFlQRV9TVEFU",
            "VVNfTUFYEA8SEAoMRUFUVFJUWVBFX0hQEGQSEwoPRUFUVFJUWVBFX0hQUEVS",
            "EGUSEwoPRUFUVFJUWVBFX01BWEhQEGYSFgoSRUFUVFJUWVBFX01BWEhQUEVS",
            "EGcSEQoNRUFUVFJUWVBFX0FUSxBoEhQKEEVBVFRSVFlQRV9BVEtQRVIQaRIR",
            "Cg1FQVRUUlRZUEVfREVGEG4SFAoQRUFUVFJUWVBFX0RFRlBFUhBvEhIKDkVB",
            "VFRSVFlQRV9NREVGEHgSFQoRRUFUVFJUWVBFX01ERUZQRVIQeRIXChJFQVRU",
            "UlRZUEVfQ1JJVFJBVEUQyAESGgoVRUFUVFJUWVBFX0NSSVRERUZSQVRFEMkB",
            "EhsKFkVBVFRSVFlQRV9DUklUREFNR0VQRVIQ0gESHgoZRUFUVFJUWVBFX0NS",
            "SVREQU1HRURFRlBFUhDTARIZChRFQVRUUlRZUEVfQlJFQUtSQVRJTxDcARIc",
            "ChdFQVRUUlRZUEVfQlJFQUtBVEtSQVRJTxDdARIcChdFQVRUUlRZUEVfQlJF",
            "QUtERUZSQVRJTxDeARIeChlFQVRUUlRZUEVfUEVORVRSQVRJT05SQVRFEOYB",
            "EiEKHEVBVFRSVFlQRV9QRU5FVFJBVElPTkFUS1JBVEUQ5wESIQocRUFUVFJU",
            "WVBFX1BFTkVUUkFUSU9OREVGUkFURRDoARIaChVFQVRUUlRZUEVfQlJFQUtN",
            "UkFUSU8Q8AESHQoYRUFUVFJUWVBFX0JSRUFLTUFUS1JBVElPEPEBEh0KGEVB",
            "VFRSVFlQRV9CUkVBS01ERUZSQVRJTxDyARIfChpFQVRUUlRZUEVfUEVORVRS",
            "QVRJT05NUkFURRD6ARIiCh1FQVRUUlRZUEVfUEVORVRSQVRJT05NQVRLUkFU",
            "RRD7ARIiCh1FQVRUUlRZUEVfUEVORVRSQVRJT05NREVGUkFURRD8ARIUCg9F",
            "QVRUUlRZUEVfRVRIRVIQrAISFwoSRUFUVFJUWVBFX0VUSEVSUEVSEK0CEhcK",
            "EkVBVFRSVFlQRV9NQVhFVEhFUhCuAhIaChVFQVRUUlRZUEVfTUFYRVRIRVJQ",
            "RVIQrwISGwoWRUFUVFJUWVBFX0VUSEVSUkVDT1ZFUhCwAhIeChlFQVRUUlRZ",
            "UEVfRVRIRVJSRUNPVkVSUEVSELECEh0KGEVBVFRSVFlQRV9FVEhFUlJFQ09W",
            "RVJDRBCyAhIgChtFQVRUUlRZUEVfRVRIRVJSRUNPVkVSQ0RQRVIQswISGAoT",
            "RUFUVFJUWVBFX0VUSEVSQ09TVBC0AhIbChZFQVRUUlRZUEVfRVRIRVJDT1NU",
            "UEVSELUCEhUKEEVBVFRSVFlQRV9FTkVSR1kQtgISGAoTRUFUVFJUWVBFX0VO",
            "RVJHWVBFUhC3AhIYChNFQVRUUlRZUEVfTUFYRU5FUkdZELgCEhsKFkVBVFRS",
            "VFlQRV9NQVhFTkVSR1lQRVIQuQISHAoXRUFUVFJUWVBFX0VORVJHWVJFQ09W",
            "RVIQugISHwoaRUFUVFJUWVBFX0VORVJHWVJFQ09WRVJQRVIQuwISHgoZRUFU",
            "VFJUWVBFX0VORVJHWVJFQ09WRVJDRBC8AhIhChxFQVRUUlRZUEVfRU5FUkdZ",
            "UkVDT1ZFUkNEUEVSEL0CEhsKFkVBVFRSVFlQRV9FTkVSR1lDSEFOR0UQvgIS",
            "HgoZRUFUVFJUWVBFX0VORVJHWUNIQU5HRVBFUhC/AhIYChNFQVRUUlRZUEVf",
            "U0hJRUxEREVGEMACEhsKFkVBVFRSVFlQRV9TSElFTERERUZQRVIQwQISHwoa",
            "RUFUVFJUWVBFX1NISUVMREJZTUFYSFBQRVIQwgISHQoYRUFUVFJUWVBFX1NI",
            "SUVMREJZQVRLUEVSEMMCEh0KGEVBVFRSVFlQRV9TSElFTERCWURFRlBFUhDE",
            "AhIeChlFQVRUUlRZUEVfU0hJRUxEQllNREVGUEVSEMUCEhYKEUVBVFRSVFlQ",
            "RV9NT1ZFU1BEEMoCEhkKFEVBVFRSVFlQRV9NT1ZFU1BEUEVSEMsCEhwKF0VB",
            "VFRSVFlQRV9CQVNFTU9WRVNQRUVEEMwCEh8KGkVBVFRSVFlQRV9CQVNFTU9W",
            "RVNQRUVEUEVSEM0CEhsKFkVBVFRSVFlQRV9NQVhIUFNFQ1RJT04Q1AISGAoT",
            "RUFUVFJUWVBFX0hQU0VDVElPThDVAhIaChVFQVRUUlRZUEVfUk9UQVRFU1BF",
            "RUQQ1gISHAoXRUFUVFJUWVBFX1NUVU5SRVNJU1RQRVIQ1wISHwoaRUFUVFJU",
            "WVBFX0RJU1RVUkJSRVNJU1RQRVIQ2AISHgoZRUFUVFJUWVBFX1NJTEVOVFJF",
            "U0lTVFBFUhDZAhIdChhFQVRUUlRZUEVfVFdJTkVSRVNJU1RQRVIQ2gISGwoW",
            "RUFUVFJUWVBFX0RBTUdFUkVCT1VORBDbAhIcChdFQVRUUlRZUEVfREFNR0VW",
            "QU1QSVJJQxDcAhIbChZFQVRUUlRZUEVfUkVBTERBTUdFQVRLEN0CEh4KGUVB",
            "VFRSVFlQRV9SRUFMREFNR0VBVEtQRVIQ3gISGQoURUFUVFJUWVBFX1JBTkdF",
            "REFNR0UQ3wISGwoWRUFUVFJUWVBFX1NQQVRURVJEQU1HRRDgAhIcChdFQVRU",
            "UlRZUEVfQ0FUQVBVTFREQU1HRRDhAhIXChJFQVRUUlRZUEVfQ0RDSEFOR0UQ",
            "4gISGgoVRUFUVFJUWVBFX0NEQ0hBTkdFUEVSEOMCEhgKE0VBVFRSVFlQRV9I",
            "SVRSRVNJU1QQ5AISGwoWRUFUVFJUWVBFX1RIUk9VR0hDT1VOVBDlAhIZChRF",
            "QVRUUlRZUEVfSEVBTEVOQ1BFUhDmAhIbChZFQVRUUlRZUEVfQkVIRUFMRU5D",
            "UEVSEOcCEhkKFEVBVFRSVFlQRV9IQVRFQ0lSQ0xFEOgCEh0KGEVBVFRSVFlQ",
            "RV9IQVRFVVBQRVJCT1VORBDpAhIcChdFQVRUUlRZUEVfQlJFQUtXRUFLVElN",
            "RRDqAhIdChhFQVRUUlRZUEVfQlJFQUtSRVNFVFRJTUUQ6wISHwoaRUFUVFJU",
            "WVBFX0JBTEFOQ0VSRVNFVFRJTUUQ7AISHAoXRUFUVFJUWVBFX0RBTUdFSU5D",
            "UkVBU0UQkAMSHgoZRUFUVFJUWVBFX0VMRU1FTlRJTkNSRUFTRRCRAxIbChZF",
            "QVRUUlRZUEVfRklSRUlOQ1JFQVNFEJIDEhoKFUVBVFRSVFlQRV9JQ0VJTkNS",
            "RUFTRRCTAxIeChlFQVRUUlRZUEVfVEhVTkRFUklOQ1JFQVNFEJQDEhwKF0VB",
            "VFRSVFlQRV9FQVJUSElOQ1JFQVNFEJUDEhoKFUVBVFRSVFlQRV9QSFlJTkNS",
            "RUFTRRCWAxIaChVFQVRUUlRZUEVfQ1VUSU5DUkVBU0UQlwMSHQoYRUFUVFJU",
            "WVBFX1NUUklLRUlOQ1JFQVNFEJgDEhwKF0VBVFRSVFlQRV9TUElLRUlOQ1JF",
            "QVNFEJkDEhoKFUVBVFRSVFlQRV9EQU1HRVJFRFVDRRCaAxIcChdFQVRUUlRZ",
            "UEVfRUxFTUVOVFJFRFVDRRCbAxIZChRFQVRUUlRZUEVfRklSRVJFRFVDRRCc",
            "AxIYChNFQVRUUlRZUEVfSUNFUkVEVUNFEJ0DEhwKF0VBVFRSVFlQRV9USFVO",
            "REVSUkVEVUNFEJ4DEhoKFUVBVFRSVFlQRV9FQVJUSFJFRFVDRRCfAxIYChNF",
            "QVRUUlRZUEVfUEhZUkVEVUNFEKADEhgKE0VBVFRSVFlQRV9DVVRSRURVQ0UQ",
            "oQMSGwoWRUFUVFJUWVBFX1NUUklLRVJFRFVDRRCiAxIaChVFQVRUUlRZUEVf",
            "U1BJS0VSRURVQ0UQowMSFwoSRUFUVFJUWVBFX01BWEJSRUFLEPQDEhoKFUVB",
            "VFRSVFlQRV9NQVhCUkVBS1BFUhD1AxIVChBFQVRUUlRZUEVfTUFYQ1VUEPYD",
            "EhgKE0VBVFRSVFlQRV9NQVhDVVRQRVIQ9wMSGAoTRUFUVFJUWVBFX01BWFNU",
            "UklLRRD4AxIbChZFQVRUUlRZUEVfTUFYU1RSSUtFUEVSEPkDEhcKEkVBVFRS",
            "VFlQRV9NQVhTUElLRRD6AxIaChVFQVRUUlRZUEVfTUFYU1BJS0VQRVIQ+wMS",
            "FgoRRUFUVFJUWVBFX01BWEZJUkUQ/AMSGQoURUFUVFJUWVBFX01BWEZJUkVQ",
            "RVIQ/QMSFQoQRUFUVFJUWVBFX01BWElDRRD+AxIYChNFQVRUUlRZUEVfTUFY",
            "SUNFUEVSEP8DEhkKFEVBVFRSVFlQRV9NQVhUSFVOREVSEIAEEhwKF0VBVFRS",
            "VFlQRV9NQVhUSFVOREVSUEVSEIEEEhcKEkVBVFRSVFlQRV9NQVhFQVJUSBCC",
            "BBIaChVFQVRUUlRZUEVfTUFYRUFSVEhQRVIQgwQSGQoURUFUVFJUWVBFX01B",
            "WEJBTEFOQ0UQhAQSHAoXRUFUVFJUWVBFX01BWEJBTEFOQ0VQRVIQhQQSFwoS",
            "RUFUVFJUWVBFX05PV0JSRUFLEIgEEhoKFUVBVFRSVFlQRV9OT1dCUkVBS1BF",
            "UhCJBBIVChBFQVRUUlRZUEVfTk9XQ1VUEIoEEhgKE0VBVFRSVFlQRV9OT1dD",
            "VVRQRVIQiwQSGAoTRUFUVFJUWVBFX05PV1NUUklLRRCMBBIbChZFQVRUUlRZ",
            "UEVfTk9XU1RSSUtFUEVSEI0EEhcKEkVBVFRSVFlQRV9OT1dTUElLRRCOBBIa",
            "ChVFQVRUUlRZUEVfTk9XU1BJS0VQRVIQjwQSFgoRRUFUVFJUWVBFX05PV0ZJ",
            "UkUQkAQSGQoURUFUVFJUWVBFX05PV0ZJUkVQRVIQkQQSFQoQRUFUVFJUWVBF",
            "X05PV0lDRRCSBBIYChNFQVRUUlRZUEVfTk9XSUNFUEVSEJMEEhkKFEVBVFRS",
            "VFlQRV9OT1dUSFVOREVSEJQEEhwKF0VBVFRSVFlQRV9OT1dUSFVOREVSUEVS",
            "EJUEEhcKEkVBVFRSVFlQRV9OT1dFQVJUSBCWBBIaChVFQVRUUlRZUEVfTk9X",
            "RUFSVEhQRVIQlwQSGQoURUFUVFJUWVBFX05PV0JBTEFOQ0UQmAQSHAoXRUFU",
            "VFJUWVBFX05PV0JBTEFOQ0VQRVIQmQQSGgoVRUFUVFJUWVBFX0JSRUFLQURE",
            "UEVSEJwEEhgKE0VBVFRSVFlQRV9DVVRBRERQRVIQnQQSGwoWRUFUVFJUWVBF",
            "X1NUUklLRUFERFBFUhCeBBIaChVFQVRUUlRZUEVfU1BJS0VBRERQRVIQnwQS",
            "GQoURUFUVFJUWVBFX0ZJUkVBRERQRVIQoAQSGAoTRUFUVFJUWVBFX0lDRUFE",
            "RFBFUhChBBIcChdFQVRUUlRZUEVfVEhVTkRFUkFERFBFUhCiBBIaChVFQVRU",
            "UlRZUEVfRUFSVEhBRERQRVIQowQSHAoXRUFUVFJUWVBFX0JBTEFOQ0VBRERQ",
            "RVIQpAQSGQoURUFUVFJUWVBFX0JSRUFLVElNRVMQpgQSFwoSRUFUVFJUWVBF",
            "X0NVVFRJTUVTEKcEEhoKFUVBVFRSVFlQRV9TVFJJS0VUSU1FUxCoBBIZChRF",
            "QVRUUlRZUEVfU1BJS0VUSU1FUxCpBBIYChNFQVRUUlRZUEVfRklSRVRJTUVT",
            "EKoEEhcKEkVBVFRSVFlQRV9JQ0VUSU1FUxCrBBIbChZFQVRUUlRZUEVfVEhV",
            "TkRFUlRJTUVTEKwEEhkKFEVBVFRSVFlQRV9FQVJUSFRJTUVTEK0EEhsKFkVB",
            "VFRSVFlQRV9CQUxBTkNFVElNRVMQrgQSHgoZRUFUVFJUWVBFX0JSRUFLRFBJ",
            "TkNSRUFTRRCwBBIcChdFQVRUUlRZUEVfQ1VURFBJTkNSRUFTRRCxBBIfChpF",
            "QVRUUlRZUEVfU1RSSUtFRFBJTkNSRUFTRRCyBBIeChlFQVRUUlRZUEVfU1BJ",
            "S0VEUElOQ1JFQVNFELMEEh0KGEVBVFRSVFlQRV9GSVJFRFBJTkNSRUFTRRC0",
            "BBIcChdFQVRUUlRZUEVfSUNFRFBJTkNSRUFTRRC1BBIgChtFQVRUUlRZUEVf",
            "VEhVTkRFUkRQSU5DUkVBU0UQtgQSHgoZRUFUVFJUWVBFX0VBUlRIRFBJTkNS",
            "RUFTRRC3BBIgChtFQVRUUlRZUEVfQkFMQU5DRURQSU5DUkVBU0UQuAQSHAoX",
            "RUFUVFJUWVBFX0JSRUFLRFBSRURVQ0UQugQSGgoVRUFUVFJUWVBFX0NVVERQ",
            "UkVEVUNFELsEEh0KGEVBVFRSVFlQRV9TVFJJS0VEUFJFRFVDRRC8BBIcChdF",
            "QVRUUlRZUEVfU1BJS0VEUFJFRFVDRRC9BBIbChZFQVRUUlRZUEVfRklSRURQ",
            "UkVEVUNFEL4EEhoKFUVBVFRSVFlQRV9JQ0VEUFJFRFVDRRC/BBIeChlFQVRU",
            "UlRZUEVfVEhVTkRFUkRQUkVEVUNFEMAEEhwKF0VBVFRSVFlQRV9FQVJUSERQ",
            "UkVEVUNFEMEEEh4KGUVBVFRSVFlQRV9CQUxBTkNFRFBSRURVQ0UQwgQSEgoN",
            "RUFUVFJUWVBFX01BWBCACCqFCwoPRUF0dHJTdGF0dXNUeXBlEhMKD0VBVFRS",
            "U1RBVFVTX01JThAAEhMKD0VBVFRSU1RBVFVTX0ZMWRABEhYKEkVBVFRSU1RB",
            "VFVTX1BPSVNPThACEhQKEEVBVFRSU1RBVFVTX0RPV04QAxIUChBFQVRUUlNU",
            "QVRVU19TVFVOEAQSFgoSRUFUVFJTVEFUVVNfRlJFRVpFEAUSFAoQRUFUVFJT",
            "VEFUVVNfQlVSThAGEhUKEUVBVFRSU1RBVFVTX0NIQU9TEAcSFQoRRUFUVFJT",
            "VEFUVVNfU1RPTkUQCBIZChVFQVRUUlNUQVRVU19QQVJBTFlTSVMQCRIYChRF",
            "QVRUUlNUQVRVU19CTEFDS1NBThAKEhUKEUVBVFRSU1RBVFVTX0JMT09EEAsS",
            "HQoZRUFUVFJTVEFUVVNfUEFSQUxZU0lTX05FVxAMEhUKEUVBVFRSU1RBVFVT",
            "X0JSRUFLEA0SGwoXRUFUVFJTVEFUVVNfSU5WSU5DSUJMRTIQDhIaChZFQVRU",
            "UlNUQVRVU19TVVBFUkFSTU9SECASIAocRUFUVFJTVEFUVVNfU1VQRVJBUk1P",
            "Ul9OT0hJVBAhEiEKHUVBVFRSU1RBVFVTX1NVUEVSQVJNT1JfTk9IRUxQECIS",
            "FAoQRUFUVFJTVEFUVVNfSElERRAjEhkKFUVBVFRSU1RBVFVTX0xFQURTS0lM",
            "TBAkEhYKEkVBVFRSU1RBVFVTX05PTU9WRRAlEhsKF0VBVFRSU1RBVFVTX05P",
            "Q0hFQ0tDT1NUECYSGgoWRUFUVFJTVEFUVVNfSU5WSU5DSUJMRRAnEhgKFEVB",
            "VFRSU1RBVFVTX05PSEVBTEVEECgSFgoSRUFUVFJTVEFUVVNfU0hJRUxEECkS",
            "FwoTRUFUVFJTVEFUVVNfUFJPVEVDVBAqEhYKEkVBVFRSU1RBVFVTX05BVFVS",
            "RRArEhUKEUVBVFRSU1RBVFVTX0JMSU5LECwSGQoVRUFUVFJTVEFUVVNfTk9T",
            "S0lMTEVEEC0SHgoaRUFUVFJTVEFUVVNfSFVSVEVRVUFMU09ORVcQLhIVChFF",
            "QVRUUlNUQVRVU19UV0lORRAvEhcKE0VBVFRSU1RBVFVTX1NJTEVOQ0UQMBIV",
            "ChFFQVRUUlNUQVRVU19UQVVOVBAxEhsKF0VBVFRSU1RBVFVTX1NIQVJFREFN",
            "QUdFEDISGQoVRUFUVFJTVEFUVVNfTk9DSEVDS0NEEDMSHwobRUFUVFJTVEFU",
            "VVNfQkFSUklFUl9JTlZBTElEEDQSIwofRUFUVFJTVEFUVVNfSU1NVU5FX0ZB",
            "VEFMX0RBTUFHRRA1EhcKE0VBVFRSU1RBVFVTX0JFSElURUQQNhIXChNFQVRU",
            "UlNUQVRVU19TVEVBTFRIEDcSIQodRUFUVFJTVEFUVVNfU1VQRVJBUk1PUl9O",
            "T0RPV04QOBIgChxFQVRUUlNUQVRVU19TVVBFUkFSTU9SX05PRkxZEDkSHwob",
            "RUFUVFJTVEFUVVNfREFNQUdFX0NSSVRTSE9XEDoSGQoVRUFUVFJTVEFUVVNf",
            "TUFHSUNfSUNFEDsSGgoWRUFUVFJTVEFUVVNfTUFHSUNfRklSRRA8EhsKF0VB",
            "VFRSU1RBVFVTX01BR0lDX0VBUlRIED0SHQoZRUFUVFJTVEFUVVNfTUFHSUNf",
            "VEhVTkRFUhA+EhoKFkVBVFRSU1RBVFVTX0lNQkFMQU5DRTEQRhIaChZFQVRU",
            "UlNUQVRVU19JTUJBTEFOQ0UyEEcSHAoYRUFUVFJTVEFUVVNfU0hBUkVNSVNT",
            "SUxFEGASGgoWRUFUVFJTVEFUVVNfQVVUT1JFTElWRRBhEhkKFUVBVFRSU1RB",
            "VFVTX0lOQUxDSEVNWRBiEhQKD0VBVFRSU1RBVFVTX01BWBCgASrAAQoMRUVs",
            "ZW1lbnRUeXBlEhQKEEVFTEVNRU5UX0lOVkFMSUQQABIRCg1FRUxFTUVOVF9G",
            "SVJFEAESEAoMRUVMRU1FTlRfSUNFEAISFAoQRUVMRU1FTlRfVEhVTkRFUhAD",
            "EhIKDkVFTEVNRU5UX0VBUlRIEAQSEAoMRUVMRU1FTlRfQ1VUEAUSEwoPRUVM",
            "RU1FTlRfU1RSSUtFEAYSEgoORUVMRU1FTlRfU1BJS0UQBxIQCgxFRUxFTUVO",
            "VF9NQVgQCEIHWgUuO0NtZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cmd.ENineDataType), typeof(global::Cmd.EItemNineDataType), typeof(global::Cmd.EAttrType), typeof(global::Cmd.EAttrStatusType), typeof(global::Cmd.EElementType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 需要九屏同步的数据类型
  /// </summary>
  public enum ENineDataType {
    [pbr::OriginalName("ENINEDATATYPE_MIN")] Min = 0,
    /// <summary>
    /// 装备的武器id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_WEAPON")] Weapon = 1,
    /// <summary>
    /// 装备的头饰id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_HEAD")] Head = 2,
    /// <summary>
    /// 装备的耳饰id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_EARRINGS")] Earrings = 3,
    /// <summary>
    /// 装备的面饰id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_FACE")] Face = 4,
    /// <summary>
    /// 装备的嘴饰id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_MOUTH")] Mouth = 5,
    /// <summary>
    /// 装备的背饰id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_BACK")] Back = 6,
    /// <summary>
    /// 装备的尾饰id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_TAIL")] Tail = 7,
    /// <summary>
    /// 装备的时装id
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_FASHION")] Fashion = 8,
    /// <summary>
    ///  状态
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_STATUS")] Status = 15,
    /// <summary>
    ///  击杀者名字
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_KILLERNAME")] Killername = 16,
    /// <summary>
    ///  npc交互数据
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_NPC_INTERACTION")] NpcInteraction = 17,
    /// <summary>
    /// 战斗状态
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_FIGHTSTATUS")] Fightstatus = 20,
    /// <summary>
    /// 当前战斗锁定ID
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_CUR_LOCKID")] CurLockid = 21,
    /// <summary>
    /// 装备ID列表-仅仅npc或者怪物用到
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_EQUIP_IDS")] EquipIds = 22,
    /// <summary>
    /// 阵营ID
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_CAMP_ID")] CampId = 23,
    /// <summary>
    /// 等级
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_ROLELEVEL")] Rolelevel = 24,
    /// <summary>
    /// 伙伴经验
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_ROLEEXP")] Roleexp = 25,
    /// <summary>
    /// 击杀者ID 不会存档 只做死亡事件触发时的逻辑用
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_KILLERID")] Killerid = 26,
    /// <summary>
    /// 拔刀状态
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_SWORDSTATE")] Swordstate = 27,
    /// <summary>
    /// 捏人数据
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_PERSONALITYDATA")] Personalitydata = 28,
    /// <summary>
    /// 怒气状态
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_ANGERSTATE")] Angerstate = 29,
    /// <summary>
    ///  非战斗状态的子状态（猫的坐下状态等）
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_IDLE_SUBSTATUS")] IdleSubstatus = 30,
    /// <summary>
    ///  抱着猫的guid变化
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_CATGUID")] Catguid = 31,
    /// <summary>
    ///  自身作为载具时的乘客ID
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_PASSENGERS")] Passengers = 32,
    /// <summary>
    ///  自身作为乘客时的载具ID
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_VEHICLE")] Vehicle = 33,
    /// <summary>
    ///  与武器的交互状态
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_WEAPONINTERACT")] Weaponinteract = 34,
    /// <summary>
    ///  护盾状态 EBarrierStatusType
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_BARRIERSTATUS")] Barrierstatus = 35,
    /// <summary>
    ///  Boss当前的阶段
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_BOSSSTAGE")] Bossstage = 36,
    /// <summary>
    ///  战斗ID
    /// </summary>
    [pbr::OriginalName("ENINEDATATYPE_COMBAT_ID")] CombatId = 37,
    [pbr::OriginalName("ENINEDATATYPE_MAX")] Max = 38,
  }

  public enum EItemNineDataType {
    [pbr::OriginalName("EITEM_NINEDATATYPE_MIN")] Min = 0,
    /// <summary>
    ///  朝向
    /// </summary>
    [pbr::OriginalName("EITEM_NINEDATATYPE_DIR")] Dir = 1,
    /// <summary>
    ///  交互状态
    /// </summary>
    [pbr::OriginalName("EITEM_NINEDATATYPE_INTERACTION")] Interaction = 2,
    /// <summary>
    ///  自身作为载具时的乘客ID
    /// </summary>
    [pbr::OriginalName("EITEM_NINEDATATYPE_PASSENGERS")] Passengers = 3,
    /// <summary>
    ///  自身作为乘客时的载具ID
    /// </summary>
    [pbr::OriginalName("EITEM_NINEDATATYPE_VEHICLE")] Vehicle = 4,
    /// <summary>
    ///  模型高度
    /// </summary>
    [pbr::OriginalName("EITEM_NINEDATATYPE_MODEL_HEIGHT")] ModelHeight = 6,
    /// <summary>
    ///  模型宽度
    /// </summary>
    [pbr::OriginalName("EITEM_NINEDATATYPE_MODEL_WIDTH")] ModelWidth = 7,
    /// <summary>
    ///  模型长度
    /// </summary>
    [pbr::OriginalName("EITEM_NINEDATATYPE_MODEL_LENGTH")] ModelLength = 8,
    [pbr::OriginalName("EITEM_NINEDATATYPE_MAX")] Max = 9,
  }

  public enum EAttrType {
    [pbr::OriginalName("EATTRTYPE_MIN")] Min = 0,
    /// <summary>
    /// 角色经验
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_EXP")] Exp = 1,
    /// <summary>
    /// 角色等级
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_LV")] Lv = 2,
    /// <summary>
    /// 属性状态1
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STATUS1")] Status1 = 10,
    /// <summary>
    /// 属性状态2
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STATUS2")] Status2 = 11,
    /// <summary>
    /// 属性状态3
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STATUS3")] Status3 = 12,
    /// <summary>
    /// 属性状态4
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STATUS4")] Status4 = 13,
    /// <summary>
    /// 属性状态5
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STATUS5")] Status5 = 14,
    /// <summary>
    /// 属性状态数据字段 MAX  范围检测使用
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STATUS_MAX")] StatusMax = 15,
    /// <summary>
    /// 当前生命
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_HP")] Hp = 100,
    /// <summary>
    /// 当前生命%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_HPPER")] Hpper = 101,
    /// <summary>
    /// 生命上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXHP")] Maxhp = 102,
    /// <summary>
    /// 生命上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXHPPER")] Maxhpper = 103,
    /// <summary>
    /// 攻击力
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ATK")] Atk = 104,
    /// <summary>
    /// 攻击力%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ATKPER")] Atkper = 105,
    /// <summary>
    /// 物理防御
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_DEF")] Def = 110,
    /// <summary>
    /// 物理防御%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_DEFPER")] Defper = 111,
    /// <summary>
    /// 魔法防御
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MDEF")] Mdef = 120,
    /// <summary>
    /// 魔法防御%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MDEFPER")] Mdefper = 121,
    /// <summary>
    /// 暴击率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CRITRATE")] Critrate = 200,
    /// <summary>
    /// 暴击减免率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CRITDEFRATE")] Critdefrate = 201,
    /// <summary>
    /// 暴击伤害%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CRITDAMGEPER")] Critdamgeper = 210,
    /// <summary>
    /// 暴击伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CRITDAMGEDEFPER")] Critdamgedefper = 211,
    /// <summary>
    /// 最终破甲率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKRATIO")] Breakratio = 220,
    /// <summary>
    /// 破甲率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKATKRATIO")] Breakatkratio = 221,
    /// <summary>
    /// 破甲减免率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKDEFRATIO")] Breakdefratio = 222,
    /// <summary>
    /// 最终物理穿透%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PENETRATIONRATE")] Penetrationrate = 230,
    /// <summary>
    /// 物理穿透率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PENETRATIONATKRATE")] Penetrationatkrate = 231,
    /// <summary>
    /// 物理穿透减免率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PENETRATIONDEFRATE")] Penetrationdefrate = 232,
    /// <summary>
    /// 最终破魔率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKMRATIO")] Breakmratio = 240,
    /// <summary>
    /// 破魔率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKMATKRATIO")] Breakmatkratio = 241,
    /// <summary>
    /// 破魔减免率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKMDEFRATIO")] Breakmdefratio = 242,
    /// <summary>
    /// 最终魔法穿透%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PENETRATIONMRATE")] Penetrationmrate = 250,
    /// <summary>
    /// 魔法穿透率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PENETRATIONMATKRATE")] Penetrationmatkrate = 251,
    /// <summary>
    /// 魔法穿透减免率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PENETRATIONMDEFRATE")] Penetrationmdefrate = 252,
    /// <summary>
    /// 当前以太
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHER")] Ether = 300,
    /// <summary>
    /// 当前以太%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHERPER")] Etherper = 301,
    /// <summary>
    /// 以太上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXETHER")] Maxether = 302,
    /// <summary>
    /// 以太上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXETHERPER")] Maxetherper = 303,
    /// <summary>
    /// 以太恢复速度
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHERRECOVER")] Etherrecover = 304,
    /// <summary>
    /// 以太恢复速度%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHERRECOVERPER")] Etherrecoverper = 305,
    /// <summary>
    /// 以太恢复间隔
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHERRECOVERCD")] Etherrecovercd = 306,
    /// <summary>
    /// 以太恢复间隔%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHERRECOVERCDPER")] Etherrecovercdper = 307,
    /// <summary>
    /// 以太消耗修正
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHERCOST")] Ethercost = 308,
    /// <summary>
    /// 以太消耗修正%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ETHERCOSTPER")] Ethercostper = 309,
    /// <summary>
    /// 当前能量
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGY")] Energy = 310,
    /// <summary>
    /// 当前能量%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGYPER")] Energyper = 311,
    /// <summary>
    /// 能量上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXENERGY")] Maxenergy = 312,
    /// <summary>
    /// 能量上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXENERGYPER")] Maxenergyper = 313,
    /// <summary>
    /// 能量恢复速度
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGYRECOVER")] Energyrecover = 314,
    /// <summary>
    /// 能量恢复速度%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGYRECOVERPER")] Energyrecoverper = 315,
    /// <summary>
    /// 能量恢复间隔
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGYRECOVERCD")] Energyrecovercd = 316,
    /// <summary>
    /// 能量恢复间隔%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGYRECOVERCDPER")] Energyrecovercdper = 317,
    /// <summary>
    /// 能量消耗修正
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGYCHANGE")] Energychange = 318,
    /// <summary>
    /// 能量消耗修正%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ENERGYCHANGEPER")] Energychangeper = 319,
    /// <summary>
    /// 护盾
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SHIELDDEF")] Shielddef = 320,
    /// <summary>
    /// 护盾%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SHIELDDEFPER")] Shielddefper = 321,
    /// <summary>
    /// 生命百分比的护盾
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SHIELDBYMAXHPPER")] Shieldbymaxhpper = 322,
    /// <summary>
    /// 攻击力百分比的护盾
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SHIELDBYATKPER")] Shieldbyatkper = 323,
    /// <summary>
    /// 物防百分比的护盾
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SHIELDBYDEFPER")] Shieldbydefper = 324,
    /// <summary>
    /// 魔防百分比的护盾
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SHIELDBYMDEFPER")] Shieldbymdefper = 325,
    /// <summary>
    /// 移动速度
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MOVESPD")] Movespd = 330,
    /// <summary>
    /// 移动速度倍率%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MOVESPDPER")] Movespdper = 331,
    /// <summary>
    /// 默认移动速度
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BASEMOVESPEED")] Basemovespeed = 332,
    /// <summary>
    /// 默认移动速率
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BASEMOVESPEEDPER")] Basemovespeedper = 333,
    /// <summary>
    /// 血条数量上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXHPSECTION")] Maxhpsection = 340,
    /// <summary>
    /// 当前血条数量
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_HPSECTION")] Hpsection = 341,
    /// <summary>
    /// 转身速率
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ROTATESPEED")] Rotatespeed = 342,
    /// <summary>
    /// 强控抗性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STUNRESISTPER")] Stunresistper = 343,
    /// <summary>
    /// 仇恨关系抗性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_DISTURBRESISTPER")] Disturbresistper = 344,
    /// <summary>
    /// 沉默抗性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SILENTRESISTPER")] Silentresistper = 345,
    /// <summary>
    /// 禁锢抗性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_TWINERESISTPER")] Twineresistper = 346,
    /// <summary>
    /// 伤害反弹%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_DAMGEREBOUND")] Damgerebound = 347,
    /// <summary>
    /// 伤害吸血比例
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_DAMGEVAMPIRIC")] Damgevampiric = 348,
    /// <summary>
    /// 真实伤害攻击力
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_REALDAMGEATK")] Realdamgeatk = 349,
    /// <summary>
    /// 真实伤害攻击力%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_REALDAMGEATKPER")] Realdamgeatkper = 350,
    /// <summary>
    /// 范围伤害%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_RANGEDAMGE")] Rangedamge = 351,
    /// <summary>
    /// 溅射伤害%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SPATTERDAMGE")] Spatterdamge = 352,
    /// <summary>
    /// 弹射伤害%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CATAPULTDAMGE")] Catapultdamge = 353,
    /// <summary>
    /// 冷却时间修正
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CDCHANGE")] Cdchange = 354,
    /// <summary>
    /// 冷却时间修正%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CDCHANGEPER")] Cdchangeper = 355,
    /// <summary>
    /// 打击力度抵抗
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_HITRESIST")] Hitresist = 356,
    /// <summary>
    /// 弹道穿透数量
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_THROUGHCOUNT")] Throughcount = 357,
    /// <summary>
    /// 治疗效果加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_HEALENCPER")] Healencper = 358,
    /// <summary>
    /// 受到治疗效果加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BEHEALENCPER")] Behealencper = 359,
    /// <summary>
    /// 吸引仇恨范围
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_HATECIRCLE")] Hatecircle = 360,
    /// <summary>
    /// 仇恨上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_HATEUPPERBOUND")] Hateupperbound = 361,
    /// <summary>
    /// Break虚弱时间
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKWEAKTIME")] Breakweaktime = 362,
    /// <summary>
    /// Break保护时间
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKRESETTIME")] Breakresettime = 363,
    /// <summary>
    /// 失衡重置时间
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BALANCERESETTIME")] Balanceresettime = 364,
    /// <summary>
    /// 伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_DAMGEINCREASE")] Damgeincrease = 400,
    /// <summary>
    /// 元素伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ELEMENTINCREASE")] Elementincrease = 401,
    /// <summary>
    /// 火元素伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_FIREINCREASE")] Fireincrease = 402,
    /// <summary>
    /// 冰元素伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ICEINCREASE")] Iceincrease = 403,
    /// <summary>
    /// 电元素伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_THUNDERINCREASE")] Thunderincrease = 404,
    /// <summary>
    /// 土元素伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_EARTHINCREASE")] Earthincrease = 405,
    /// <summary>
    /// 物理伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PHYINCREASE")] Phyincrease = 406,
    /// <summary>
    /// 斩属性伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CUTINCREASE")] Cutincrease = 407,
    /// <summary>
    /// 打属性伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STRIKEINCREASE")] Strikeincrease = 408,
    /// <summary>
    /// 突属性伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SPIKEINCREASE")] Spikeincrease = 409,
    /// <summary>
    /// 伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_DAMGEREDUCE")] Damgereduce = 410,
    /// <summary>
    /// 元素伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ELEMENTREDUCE")] Elementreduce = 411,
    /// <summary>
    /// 火元素伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_FIREREDUCE")] Firereduce = 412,
    /// <summary>
    /// 冰元素伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ICEREDUCE")] Icereduce = 413,
    /// <summary>
    /// 电元素伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_THUNDERREDUCE")] Thunderreduce = 414,
    /// <summary>
    /// 土元素伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_EARTHREDUCE")] Earthreduce = 415,
    /// <summary>
    /// 物理伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_PHYREDUCE")] Phyreduce = 416,
    /// <summary>
    /// 斩属性伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CUTREDUCE")] Cutreduce = 417,
    /// <summary>
    /// 打属性伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STRIKEREDUCE")] Strikereduce = 418,
    /// <summary>
    /// 突属性伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SPIKEREDUCE")] Spikereduce = 419,
    /// <summary>
    /// Break值耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXBREAK")] Maxbreak = 500,
    /// <summary>
    /// Break值耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXBREAKPER")] Maxbreakper = 501,
    /// <summary>
    /// 斩异常耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXCUT")] Maxcut = 502,
    /// <summary>
    /// 斩异常耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXCUTPER")] Maxcutper = 503,
    /// <summary>
    /// 打异常耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXSTRIKE")] Maxstrike = 504,
    /// <summary>
    /// 打异常耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXSTRIKEPER")] Maxstrikeper = 505,
    /// <summary>
    /// 突异常耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXSPIKE")] Maxspike = 506,
    /// <summary>
    /// 突异常耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXSPIKEPER")] Maxspikeper = 507,
    /// <summary>
    /// 火异常耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXFIRE")] Maxfire = 508,
    /// <summary>
    /// 火异常耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXFIREPER")] Maxfireper = 509,
    /// <summary>
    /// 冰异常耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXICE")] Maxice = 510,
    /// <summary>
    /// 冰异常耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXICEPER")] Maxiceper = 511,
    /// <summary>
    /// 雷异常耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXTHUNDER")] Maxthunder = 512,
    /// <summary>
    /// 雷异常耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXTHUNDERPER")] Maxthunderper = 513,
    /// <summary>
    /// 土异常耐性上限
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXEARTH")] Maxearth = 514,
    /// <summary>
    /// 土异常耐性上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXEARTHPER")] Maxearthper = 515,
    /// <summary>
    /// 失衡耐性值上限 
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXBALANCE")] Maxbalance = 516,
    /// <summary>
    /// 失衡耐性值上限%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_MAXBALANCEPER")] Maxbalanceper = 517,
    /// <summary>
    /// 当前Break值耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWBREAK")] Nowbreak = 520,
    /// <summary>
    /// 当前Break值耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWBREAKPER")] Nowbreakper = 521,
    /// <summary>
    /// 当前斩异常耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWCUT")] Nowcut = 522,
    /// <summary>
    /// 当前斩异常耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWCUTPER")] Nowcutper = 523,
    /// <summary>
    /// 当前打异常耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWSTRIKE")] Nowstrike = 524,
    /// <summary>
    /// 当前打异常耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWSTRIKEPER")] Nowstrikeper = 525,
    /// <summary>
    /// 当前突异常耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWSPIKE")] Nowspike = 526,
    /// <summary>
    /// 当前突异常耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWSPIKEPER")] Nowspikeper = 527,
    /// <summary>
    /// 当前火异常耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWFIRE")] Nowfire = 528,
    /// <summary>
    /// 当前火异常耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWFIREPER")] Nowfireper = 529,
    /// <summary>
    /// 当前冰异常耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWICE")] Nowice = 530,
    /// <summary>
    /// 当前冰异常耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWICEPER")] Nowiceper = 531,
    /// <summary>
    /// 当前雷异常耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWTHUNDER")] Nowthunder = 532,
    /// <summary>
    /// 当前雷异常耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWTHUNDERPER")] Nowthunderper = 533,
    /// <summary>
    /// 当前土异常耐性
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWEARTH")] Nowearth = 534,
    /// <summary>
    /// 当前土异常耐性%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWEARTHPER")] Nowearthper = 535,
    /// <summary>
    /// 当前失衡耐性值
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWBALANCE")] Nowbalance = 536,
    /// <summary>
    /// 当前失衡耐性值%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_NOWBALANCEPER")] Nowbalanceper = 537,
    /// <summary>
    /// Break异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKADDPER")] Breakaddper = 540,
    /// <summary>
    /// 斩异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CUTADDPER")] Cutaddper = 541,
    /// <summary>
    /// 打异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STRIKEADDPER")] Strikeaddper = 542,
    /// <summary>
    /// 突异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SPIKEADDPER")] Spikeaddper = 543,
    /// <summary>
    /// 火异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_FIREADDPER")] Fireaddper = 544,
    /// <summary>
    /// 冰异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ICEADDPER")] Iceaddper = 545,
    /// <summary>
    /// 雷异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_THUNDERADDPER")] Thunderaddper = 546,
    /// <summary>
    /// 土异常增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_EARTHADDPER")] Earthaddper = 547,
    /// <summary>
    /// 失衡耐性上限增加比例%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BALANCEADDPER")] Balanceaddper = 548,
    /// <summary>
    /// 进入Break异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKTIMES")] Breaktimes = 550,
    /// <summary>
    /// 进入斩异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CUTTIMES")] Cuttimes = 551,
    /// <summary>
    /// 进入打异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STRIKETIMES")] Striketimes = 552,
    /// <summary>
    /// 进入突异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SPIKETIMES")] Spiketimes = 553,
    /// <summary>
    /// 进入火异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_FIRETIMES")] Firetimes = 554,
    /// <summary>
    /// 进入冰异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ICETIMES")] Icetimes = 555,
    /// <summary>
    /// 进入雷异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_THUNDERTIMES")] Thundertimes = 556,
    /// <summary>
    /// 进入土异常次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_EARTHTIMES")] Earthtimes = 557,
    /// <summary>
    /// 进入失衡次数
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BALANCETIMES")] Balancetimes = 558,
    /// <summary>
    /// Break值伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKDPINCREASE")] Breakdpincrease = 560,
    /// <summary>
    /// 斩异常伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CUTDPINCREASE")] Cutdpincrease = 561,
    /// <summary>
    /// 打异常伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STRIKEDPINCREASE")] Strikedpincrease = 562,
    /// <summary>
    /// 突异常伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SPIKEDPINCREASE")] Spikedpincrease = 563,
    /// <summary>
    /// 火异常伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_FIREDPINCREASE")] Firedpincrease = 564,
    /// <summary>
    /// 冰异常伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ICEDPINCREASE")] Icedpincrease = 565,
    /// <summary>
    /// 雷异常伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_THUNDERDPINCREASE")] Thunderdpincrease = 566,
    /// <summary>
    /// 土异常伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_EARTHDPINCREASE")] Earthdpincrease = 567,
    /// <summary>
    /// 失衡伤害加成%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BALANCEDPINCREASE")] Balancedpincrease = 568,
    /// <summary>
    /// Break值伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BREAKDPREDUCE")] Breakdpreduce = 570,
    /// <summary>
    /// 斩异常伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_CUTDPREDUCE")] Cutdpreduce = 571,
    /// <summary>
    /// 打异常伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_STRIKEDPREDUCE")] Strikedpreduce = 572,
    /// <summary>
    /// 突异常伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_SPIKEDPREDUCE")] Spikedpreduce = 573,
    /// <summary>
    /// 火异常伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_FIREDPREDUCE")] Firedpreduce = 574,
    /// <summary>
    /// 冰异常伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_ICEDPREDUCE")] Icedpreduce = 575,
    /// <summary>
    /// 雷异常伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_THUNDERDPREDUCE")] Thunderdpreduce = 576,
    /// <summary>
    /// 土异常伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_EARTHDPREDUCE")] Earthdpreduce = 577,
    /// <summary>
    /// 失衡伤害减免%
    /// </summary>
    [pbr::OriginalName("EATTRTYPE_BALANCEDPREDUCE")] Balancedpreduce = 578,
    [pbr::OriginalName("EATTRTYPE_MAX")] Max = 1024,
  }

  /// <summary>
  ///  属性状态
  /// </summary>
  public enum EAttrStatusType {
    /// <summary>
    /// 异常状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_MIN")] EattrstatusMin = 0,
    /// <summary>
    /// 吹飞
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_FLY")] EattrstatusFly = 1,
    /// <summary>
    /// 中毒
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_POISON")] EattrstatusPoison = 2,
    /// <summary>
    /// 击倒
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_DOWN")] EattrstatusDown = 3,
    /// <summary>
    /// 眩晕
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_STUN")] EattrstatusStun = 4,
    /// <summary>
    /// 冰冻
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_FREEZE")] EattrstatusFreeze = 5,
    /// <summary>
    /// 灼烧
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_BURN")] EattrstatusBurn = 6,
    /// <summary>
    /// 恐惧状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_CHAOS")] EattrstatusChaos = 7,
    /// <summary>
    /// 石化状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_STONE")] EattrstatusStone = 8,
    /// <summary>
    /// 麻痹状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_PARALYSIS")] EattrstatusParalysis = 9,
    /// <summary>
    /// 黑化状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_BLACKSAN")] EattrstatusBlacksan = 10,
    /// <summary>
    /// 流血状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_BLOOD")] EattrstatusBlood = 11,
    /// <summary>
    /// 麻痹状态 新
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_PARALYSIS_NEW")] EattrstatusParalysisNew = 12,
    /// <summary>
    /// break状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_BREAK")] EattrstatusBreak = 13,
    /// <summary>
    ///  无敌，但可以受到buff伤害 
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_INVINCIBLE2")] EattrstatusInvincible2 = 14,
    /// <summary>
    /// 通用状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SUPERARMOR")] EattrstatusSuperarmor = 32,
    /// <summary>
    /// 霸体状态2 抵抗受击、击退
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SUPERARMOR_NOHIT")] EattrstatusSuperarmorNohit = 33,
    /// <summary>
    /// 霸体状态3 抵抗友方help位移
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SUPERARMOR_NOHELP")] EattrstatusSuperarmorNohelp = 34,
    /// <summary>
    /// 隐身状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_HIDE")] EattrstatusHide = 35,
    /// <summary>
    /// 技能的持续引导状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_LEADSKILL")] EattrstatusLeadskill = 36,
    /// <summary>
    /// 不可移动状态  只是不能走路
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_NOMOVE")] EattrstatusNomove = 37,
    /// <summary>
    /// 所有技能没有消耗的状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_NOCHECKCOST")] EattrstatusNocheckcost = 38,
    /// <summary>
    /// 无敌状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_INVINCIBLE")] EattrstatusInvincible = 39,
    /// <summary>
    /// 免疫治疗状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_NOHEALED")] EattrstatusNohealed = 40,
    /// <summary>
    /// 护盾状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SHIELD")] EattrstatusShield = 41,
    /// <summary>
    /// 防御状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_PROTECT")] EattrstatusProtect = 42,
    /// <summary>
    /// 根性状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_NATURE")] EattrstatusNature = 43,
    /// <summary>
    /// 位移、blink状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_BLINK")] EattrstatusBlink = 44,
    /// <summary>
    /// 无法成为技能目标
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_NOSKILLED")] EattrstatusNoskilled = 45,
    /// <summary>
    /// 受伤为1点
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_HURTEQUALSONEW")] EattrstatusHurtequalsonew = 46,
    /// <summary>
    /// 缠绕状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_TWINE")] EattrstatusTwine = 47,
    /// <summary>
    /// 沉默状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SILENCE")] EattrstatusSilence = 48,
    /// <summary>
    /// 嘲讽状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_TAUNT")] EattrstatusTaunt = 49,
    /// <summary>
    /// 被分担伤害
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SHAREDAMAGE")] EattrstatusSharedamage = 50,
    /// <summary>
    /// 所有技能没有CD的状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_NOCHECKCD")] EattrstatusNocheckcd = 51,
    /// <summary>
    /// 生命护盾失效状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_BARRIER_INVALID")] EattrstatusBarrierInvalid = 52,
    /// <summary>
    ///  免疫致命伤害状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_IMMUNE_FATAL_DAMAGE")] EattrstatusImmuneFatalDamage = 53,
    /// <summary>
    /// 可以被击中 与EATTRSTATUS_NOSKILLED组合使用
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_BEHITED")] EattrstatusBehited = 54,
    /// <summary>
    /// 隐身 仅表现
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_STEALTH")] EattrstatusStealth = 55,
    /// <summary>
    ///  不可被击倒
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SUPERARMOR_NODOWN")] EattrstatusSuperarmorNodown = 56,
    /// <summary>
    ///  不可被击飞
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SUPERARMOR_NOFLY")] EattrstatusSuperarmorNofly = 57,
    /// <summary>
    /// 被攻击时伤害表现为暴击
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_DAMAGE_CRITSHOW")] EattrstatusDamageCritshow = 58,
    /// <summary>
    /// 冰附魔状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_MAGIC_ICE")] EattrstatusMagicIce = 59,
    /// <summary>
    /// 火附魔状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_MAGIC_FIRE")] EattrstatusMagicFire = 60,
    /// <summary>
    /// 土附魔状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_MAGIC_EARTH")] EattrstatusMagicEarth = 61,
    /// <summary>
    /// 雷附魔状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_MAGIC_THUNDER")] EattrstatusMagicThunder = 62,
    /// <summary>
    ///  失衡1
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_IMBALANCE1")] EattrstatusImbalance1 = 70,
    /// <summary>
    ///  失衡2
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_IMBALANCE2")] EattrstatusImbalance2 = 71,
    /// <summary>
    /// 特定技能用到的状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_SHAREMISSILE")] EattrstatusSharemissile = 96,
    /// <summary>
    /// 可以自动重生状态
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_AUTORELIVE")] EattrstatusAutorelive = 97,
    /// <summary>
    /// 处在炼金阵内
    /// </summary>
    [pbr::OriginalName("EATTRSTATUS_INALCHEMY")] EattrstatusInalchemy = 98,
    [pbr::OriginalName("EATTRSTATUS_MAX")] EattrstatusMax = 160,
  }

  /// <summary>
  ///  元素类型
  /// </summary>
  public enum EElementType {
    /// <summary>
    ///  无效
    /// </summary>
    [pbr::OriginalName("EELEMENT_INVALID")] EelementInvalid = 0,
    /// <summary>
    ///  火元素
    /// </summary>
    [pbr::OriginalName("EELEMENT_FIRE")] EelementFire = 1,
    /// <summary>
    ///  冰元素
    /// </summary>
    [pbr::OriginalName("EELEMENT_ICE")] EelementIce = 2,
    /// <summary>
    ///  雷元素
    /// </summary>
    [pbr::OriginalName("EELEMENT_THUNDER")] EelementThunder = 3,
    /// <summary>
    ///  土元素
    /// </summary>
    [pbr::OriginalName("EELEMENT_EARTH")] EelementEarth = 4,
    /// <summary>
    ///  斩元素
    /// </summary>
    [pbr::OriginalName("EELEMENT_CUT")] EelementCut = 5,
    /// <summary>
    ///  打元素
    /// </summary>
    [pbr::OriginalName("EELEMENT_STRIKE")] EelementStrike = 6,
    /// <summary>
    ///  突元素
    /// </summary>
    [pbr::OriginalName("EELEMENT_SPIKE")] EelementSpike = 7,
    /// <summary>
    ///  
    /// </summary>
    [pbr::OriginalName("EELEMENT_MAX")] EelementMax = 8,
  }

  #endregion

}

#endregion Designer generated code
