// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xCmd.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cmd {

  /// <summary>Holder for reflection information generated from xCmd.proto</summary>
  public static partial class XCmdReflection {

    #region Descriptor
    /// <summary>File descriptor for xCmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static XCmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp4Q21kLnByb3RvEgNDbWQiNwoFTm9uY2USEQoJdGltZXN0YW1wGAEgASgN",
            "Eg0KBWluZGV4GAIgASgNEgwKBHNpZ24YAyABKAkigAEKCldyYXBQYWNrZXQS",
            "HQoDY21kGAEgASgOMhAuQ21kLkNvbW1hbmRMaXN0Eg8KB2NvbnRlbnQYAiAB",
            "KAwSEQoJdGltZXN0YW1wGAMgASgEEgsKA3NlcRgEIAEoDRIMCgRjb2RlGAUg",
            "ASgNEhQKDHJlY29ubmVjdHJlcRgGIAEoDSq7ZwoLQ29tbWFuZExpc3QSGAoU",
            "Q01EX0xPR0lOX1VTRVJfU1RBUlQQABIXChNDTURfUmVxTG9naW5Vc2VyQ21k",
            "EAESGQoVQ01EX0NyZWF0ZUNoYXJVc2VyQ21kEAISFwoTQ01EX1NuYXBTaG90",
            "VXNlckNtZBADEhkKFUNNRF9TZWxlY3RSb2xlVXNlckNtZBAFEhoKFkNNRF9M",
            "b2dpblJlc3VsdFVzZXJDbWQQBhIZChVDTURfRGVsZXRlQ2hhclVzZXJDbWQQ",
            "BxIYChRDTURfSGVhcnRCZWF0VXNlckNtZBAIEhkKFUNNRF9TZXJ2ZXJUaW1l",
            "VXNlckNtZBAJEhgKFENNRF9LaWNrUGFyYW1Vc2VyQ21kEA0SHwobQ01EX0Nh",
            "bmNlbERlbGV0ZUNoYXJVc2VyQ21kEA4SGgoWQ01EX0NsaWVudEZyYW1lVXNl",
            "ckNtZBAPEhcKEkNNRF9MT0dJTl9VU0VSX0VORBDHARIZChRDTURfRVJST1Jf",
            "VVNFUl9TVEFSVBDIARIWChFDTURfUmVnRXJyVXNlckNtZBDJARIXChJDTURf",
            "RVJST1JfVVNFUl9FTkQQjwMSGQoUQ01EX1NDRU5FX1VTRVJfU1RBUlQQkAMS",
            "FwoSQ01EX1NldFVzZXJEYXRhQ21kEJEDEhcKEkNNRF9TZXROaW5lRGF0YUNt",
            "ZBCSAxIWChFDTURfVXNlckdNQ29tbWFuZBCTAxIUCg9DTURfQmxhY2tTYW5D",
            "bWQQlAMSGgoVQ01EX0J1ZmZFZmZlY3RVc2VyQ21kEJUDEhQKD0NNRF9Vc2Vy",
            "RmFjZUNtZBCWAxIbChZDTURfQXR0cnNDaGFuZ2VTeW5jQ21kEJgDEh4KGUNN",
            "RF9Vc2VyQXR0ckNoYW5nZVNob3dDbWQQmQMSHAoXQ01EX1N1bW1vbkVmZmVj",
            "dFVzZXJDbWQQmgMSIgodQ01EX0JhdHRsZU9iamVjdEVmZmVjdFVzZXJDbWQQ",
            "mwMSEgoNQ01EX1JlZERvdENtZBCcAxIZChRDTURfUmVkRG90Q29uZmlybUNt",
            "ZBCdAxIbChZDTURfQ2hhbmdlU2NlbmVVc2VyQ21kEJ8DEh0KGENNRF9NaXNz",
            "aWxlRWZmZWN0VXNlckNtZBCgAxIeChlDTURfU2tpbGxCcm9hZGNhc3RVc2Vy",
            "Q21kEKEDEhoKFUNNRF9Nb3ZlRWZmZWN0VXNlckNtZBCiAxIcChdDTURfRGFt",
            "YWdlRWZmZWN0VXNlckNtZBCjAxIfChpDTURfVXBkYXRlU2tpbGxSYW5kU2Vl",
            "ZENtZBCkAxIbChZDTURfU2tpbGxSZXN1bHRVc2VyQ21kEKUDEhYKEUNNRF9D",
            "RFRpbWVVc2VyQ21kEKcDEhYKEUNNRF9SZWxpdmVVc2VyQ21kEKgDEhQKD0NN",
            "RF9Hb1RvVXNlckNtZBCpAxIaChVDTURfQnJlYWtTa2lsbFVzZXJDbWQQqgMS",
            "GwoWQ01EX0dvVG9FeGl0UG9zVXNlckNtZBCrAxIdChhDTURfU3BlY2lhbEVm",
            "ZmVjdFVzZXJDbWQQrAMSGwoWQ01EX0FuaW1Nb3ZlU3luY1Bvc0NtZBCtAxIg",
            "ChtDTURfRHluYW1pY01vdmVFZmZlY3RFbmRDbWQQrgMSGQoUQ01EX0NWaXNp",
            "dE5wY1VzZXJDbWQQrwMSHQoYQ01EX0NTdG9wVmlzaXROcGNVc2VyQ21kELAD",
            "EhsKFkNNRF9TU2hvd0RpYWxvZ1VzZXJDbWQQsQMSHQoYQ01EX0Nob29zZVBh",
            "cnRuZXJVc2VyQ21kELIDEhQKD0NNRF9UZWFtRGF0YUNtZBCzAxIXChJDTURf",
            "U2V0VGVhbVVzZXJDbWQQtAMSHAoXQ01EX1VzZXJCdWZmTmluZVN5bmNDbWQQ",
            "tQMSHgoZQ01EX1VzZXJBY3Rpb25OaW5lU3luY0NtZBC2AxIfChpDTURfTm90",
            "aWZ5SGlkZUNsb3NlVXNlckNtZBC3AxIZChRDTURfVW5sb2NraW5nTWVudUNt",
            "ZBC4AxIcChdDTURfVW5sb2NrZWRNZW51RGF0YUNtZBC5AxIaChVDTURfUmVx",
            "TWFwTGlua1VzZXJDbWQQugMSIAobQ01EX0Jyb2FkQ2FzdE1hcExpbmtVc2Vy",
            "Q21kELsDEh8KGkNNRF9Ta2lsbFJlcGxhY2VQYXJ0bmVyQ21kELwDEhUKEENN",
            "RF9Hb01hcFVzZXJDbWQQvQMSHgoZQ01EX1VzZXJFZmZlY3ROaW5lU3luY0Nt",
            "ZBC+AxIiCh1DTURfVXNlckV4cHJlc3Npb25OaW5lU3luY0NtZBC/AxIdChhD",
            "TURfVXNlclNvdW5kTmluZVN5bmNDbWQQwAMSEgoNQ01EX1BsYXlDR0NtZBDB",
            "AxIaChVDTURfVXNlclNob3dCdWJibGVDbWQQwgMSGwoWQ01EX1JldFZpc2l0",
            "TnBjVXNlckNtZBDDAxIfChpDTURfUmV0U3RvcFZpc2l0TnBjVXNlckNtZBDG",
            "AxIgChtDTURfU2tpbGxBY3RvckVmZmVjdFVzZXJDbWQQxwMSHQoYQ01EX1Vz",
            "ZXJTcGVjaWFsQWN0aW9uQ21kEMkDEhUKEENNRF9Bc2lkZVVzZXJDbWQQygMS",
            "HQoYQ01EX1NlbmRQYXJ0bmVyU291cmNlQ21kEMsDEiIKHUNNRF9Vc2VyQ29s",
            "bGVnZUdpZnRSZWNlaXZlQ21kENMDEh8KGkNNRF9Vc2VyQ29sbGVnZUdpZnRJ",
            "bmZvQ21kENQDEh4KGUNNRF9Vc2VyVXNlVW5pcXVlU2tpbGxDbWQQ4AMSHQoY",
            "Q01EX1VzZXJNb3V0aE5pbmVTeW5jQ21kEOUDEhYKEUNNRF9XZWF0aGVyQ2hh",
            "bmdlEOgDEhkKFENNRF9XWEtKQXNpZGVVc2VyQ21kEOkDEhsKFkNNRF9Hb1Rv",
            "Q29tbW9uVHJhY2VDbWQQ6gMSGgoVQ01EX1VwZGF0ZVF1ZXN0VmFyQ21kEOsD",
            "EhMKDkNNRF9SYWlkV2luQ21kEOwDEhQKD0NNRF9SYWlkQmFja0NtZBDtAxIT",
            "Cg5DTURfTG90dGVyeUNtZBDuAxIdChhDTURfU2VuZExvdHRlcnlSZXN1bHRD",
            "bWQQ7wMSGAoTQ01EX01pbmlNYXBzSW5mb0NtZBDwAxIfChpDTURfU2VuZEdN",
            "TG90dGVyeVJlc3VsdENtZBDxAxIiCh1DTURfU3luY05wY0ludGVyYWN0aW9u",
            "TW9kZUNtZBDyAxIbChZDTURfU2NlbmVSYWlkUmVzdWx0Q21kEPMDEhcKEkNN",
            "RF9DMlNCdWZmU3luY0NtZBD0AxIaChVDTURfU3luY0FjdGlvbkxpc3RDbWQQ",
            "9QMSHwoaQ01EX05wY0J1YmJsZVBlcmNlcHRpb25DbWQQ9gMSGAoTQ01EX1N5",
            "bmNVc2VyRGVhZENtZBD3AxIcChdDTURfU3luY09iamVjdFN0YXR1c0NtZBD/",
            "AxIcChdDTURfUm9vdE1vdGlvblN3aXRjaENtZBDTBBIUCg9DTURfU2V0Um9i",
            "b3RDbWQQ1AQSGgoVQ01EX1dlYWtTeW5jU3dpdGNoQ21kENUEEh4KGUNNRF9T",
            "dHJlc3NUZXN0UmVzcG9uc2VDbWQQ1gQSFwoSQ01EX1NDRU5FX1VTRVJfRU5E",
            "ENcEEhoKFUNNRF9TQ0VORV9VU0VSMl9TVEFSVBDYBBIPCgpDTURfU3lzTXNn",
            "ENoEEhgKE0NNRF9DRXhpdFBvc1VzZXJDbWQQ3AQSGgoVQ01EX0NXb3JsZEp1",
            "bXBVc2VyQ21kEN0EEiAKG0NNRF9DQXNrVW5sb2NrZWRNZW51TGlzdENtZBDe",
            "BBIVChBDTURfU1VzZXJEYXRhQ21kEOAEEhIKDUNNRF9DYXRIdWdDbWQQ4QQS",
            "FgoRQ01EX0VmZmVjdFVzZXJDbWQQ4wQSGQoUQ01EX1F1ZXJ5U2hvcEdvdEl0",
            "ZW0Q7wQSGgoVQ01EX1VwZGF0ZVNob3BHb3RJdGVtEPAEEg8KCkNNRF9PcGVu",
            "VUkQ8QQSGgoVQ01EX0ZvbGxvd1RyYW5zZmVyQ21kEPMEEhcKEkNNRF9DYWxs",
            "TnBjRnVuY0NtZBD0BBISCg1DTURfTW9kZWxTaG93EPUEEhcKEkNNRF9Tb3Vu",
            "ZEVmZmVjdENtZBD2BBIVChBDTURfQ2hhbmdlQmdtQ21kEPgEEhQKD0NNRF9H",
            "YW1lVGltZUNtZBD5BBIUCg9DTURfU2hha2VTY3JlZW4Q/AQSFwoSQ01EX05w",
            "Y0NoYW5nZUFuZ2xlEP8EEhgKE0NNRF9Hb1RvR2VhclVzZXJDbWQQggUSFQoQ",
            "Q01EX0ZvbGxvd2VyVXNlchCEBRIYChNDTURfQmVGb2xsb3dVc2VyQ21kEIUF",
            "Eh4KGUNNRF9Hb3RvTGFib3JhdG9yeVVzZXJDbWQQhwUSFwoSQ01EX1NjZW5l",
            "cnlVc2VyQ21kEIgFEhcKEkNNRF9Vc2VyQXV0b0hpdENtZBCLBRIiCh1DTURf",
            "VXBsb2FkU2NlbmVyeVBob3RvVXNlckNtZBCMBRIkCh9DTURfRG93bmxvYWRT",
            "Y2VuZXJ5UGhvdG9Vc2VyQ21kEI0FEhcKEkNNRF9CdWZmRm9yZXZlckNtZBCQ",
            "BRIfChpDTURfSW52aXRlSm9pbkhhbmRzVXNlckNtZBCRBRIcChdDTURfQnJl",
            "YWtVcEhhbmRzVXNlckNtZBCSBRIaChVDTURfSGFuZFN0YXR1c1VzZXJDbWQQ",
            "kwUSGQoUQ01EX0pvaW5IYW5kc1VzZXJDbWQQmQUSGQoUQ01EX1NoYWtlVHJl",
            "ZVVzZXJDbWQQogUSGAoTQ01EX1RyZWVMaXN0VXNlckNtZBCjBRIgChtDTURf",
            "SXRlbUltYWdlVXNlck50ZlVzZXJDbWQQpwUSGgoVQ01EX0NoYW5nZU5hbWVV",
            "c2VyQ21kEKkFEh0KGENNRF9OdGZWaXNpYmxlTnBjVXNlckNtZBCzBRIeChlD",
            "TURfVXB5dW5BdXRob3JpemF0aW9uQ21kELQFEhYKEUNNRF9Vc2VyUmVuYW1l",
            "Q21kELUFEh4KGUNNRF9FbnRlckNhcHJhQWN0aXZpdHlDbWQQtgUSEwoOQ01E",
            "X0J1eVplbnlDbWQQtwUSGgoVQ01EX0NhbGxUZWFtZXJVc2VyQ21kELgFEh8K",
            "GkNNRF9DYWxsVGVhbWVyUmVwbHlVc2VyQ21kELkFEhsKFkNNRF9TaG93U2Vy",
            "dmFudFVzZXJDbWQQwAUSHgoZQ01EX1JlcGxhY2VTZXJ2YW50VXNlckNtZBDB",
            "BRIXChJDTURfU2VydmFudFNlcnZpY2UQwgUSIAobQ01EX1JlY29tbWVuZFNl",
            "cnZhbnRVc2VyQ21kEMMFEh4KGUNNRF9SZWNlaXZlU2VydmFudFVzZXJDbWQQ",
            "xAUSIwoeQ01EX1NlcnZhbnRSZXdhcmRTdGF0dXNVc2VyQ21kEMUFEhsKFkNN",
            "RF9Ud2luc0FjdGlvblVzZXJDbWQQxwUSGAoTQ01EX0Jvb3RoUmVxVXNlckNt",
            "ZBDWBRIdChhDTURfQm9vdGhJbmZvU3luY1VzZXJDbWQQ1wUSIQocQ01EX0No",
            "YW5nZVVzZXJQb3NJblJhcGFpckNtZBDYBRIfChpDTURfU2VuZExvdHRlcnlQ",
            "b29sSW5mb0NtZBDaBRIgChtDTURfSW50ZXJhY3Rpb25XaXRoRW50cnlDbWQQ",
            "2wUSFwoSQ01EX0ludGVyYWN0aW9uQ21kENwFEhIKDUNNRF9QaWNrVXBDbWQQ",
            "3QUSEwoOQ01EX1B1dERvd25DbWQQ3gUSEQoMQ01EX1Rocm93Q21kEN8FEhQK",
            "D0NNRF9DYXRhcHVsdENtZBDgBRIYChNDTURfUGlja1VwUmVzdWx0Q21kEOEF",
            "EhkKFENNRF9QdXREb3duUmVzdWx0Q21kEOIFEhcKEkNNRF9UaHJvd1Jlc3Vs",
            "dENtZBDjBRIaChVDTURfQ2F0YXB1bHRSZXN1bHRDbWQQ5AUSHQoYQ01EX0lu",
            "dGVyYWN0aW9uUmVzdWx0Q21kEOUFEhoKFUNNRF9XWEtKU3RhZ2VzSW5mb0Nt",
            "ZBDmBRIVChBDTURfT25WZWhpY2xlQ21kEOgFEhsKFkNNRF9PblZlaGljbGVS",
            "ZXN1bHRDbWQQ6QUSFgoRQ01EX09mZlZlaGljbGVDbWQQ6gUSHAoXQ01EX09m",
            "ZlZlaGljbGVSZXN1bHRDbWQQ6wUSHAoXQ01EX0ludGVyYWN0aW9uRXZlbnRD",
            "bWQQ7AUSGQoUQ01EX1dYS0pDaGFsbGVuZ2VDbWQQ7QUSFwoSQ01EX0VsaXRl",
            "UmVwYWlyQ21kEO4FEh4KGUNNRF9XWEtKU3dpdGNoTWF0ZXJpYWxDbWQQ7wUS",
            "GQoUQ01EX0RhaWx5QWN0aXZpdHlDbWQQ8AUSHgoZQ01EX0RhaWx5QWN0aXZp",
            "dHlBd2FyZENtZBDxBRImCiFDTURfRGFpbHlBY3Rpdml0eUNvbXBsZXRlQXdh",
            "cmRDbWQQ8gUSGAoTQ01EX0Zhdm9yYWJpbGl0eUNtZBDzBRIgChtDTURfU2Vu",
            "ZFJlbG9naW5TZXJ2ZXJSZXFDbWQQ9AUSGwoWQ01EX0NsdWJDaGFsbGVuZ2VD",
            "R0NtZBD4BRIYChNDTURfU0NFTkVfVVNFUjJfRU5EEJ8GEh8KGkNNRF9TQ0VO",
            "RV9VU0VSX1NLSUxMX1NUQVJUEKAGEh0KGENNRF9TQ0VORV9VU0VSX1NLSUxM",
            "X0VORBDnBxIfChpDTURfU0NFTkVfVVNFUl9RVUVTVF9TVEFSVBDoBxIXChJD",
            "TURfQ2xpZW50RXZlbnRDbWQQ/gcSHwoaQ01EX0NsaWVudEV2ZW50Q2FsbGJh",
            "Y2tDbWQQ/wcSFQoQQ01EX1F1ZXN0TGlzdENtZBCACBIUCg9DTURfQWRkUXVl",
            "c3RDbWQQgQgSFAoPQ01EX0RlbFF1ZXN0Q21kEIIIEhcKEkNNRF9VcGRhdGVR",
            "dWVzdENtZBCDCBIaChVDTURfVXBkYXRlVmFyUXVlc3RDbWQQhAgSHAoXQ01E",
            "X0FjY2VwdGFibGVRdWVzdHNDbWQQhQgSGwoWQ01EX1Nob3dSZXdhcmRPbkRp",
            "YWxvZxCGCBIYChNDTURfUmV3YXJkQ29tbW9uQ21kEIcIEhoKFUNNRF9HZXRS",
            "ZXdhcmRRdWVzdENtZBCICBIbChZDTURfUXVlc3RMaXN0RGlhbG9nQ21kEIkI",
            "Eh4KGUNNRF9SZXRRdWVzdExpc3REaWFsb2dDbWQQiggSIgodQ01EX1F1ZXN0",
            "UG9zaXRpb25UcmFjZUxpc3RDbWQQiwgSGgoVQ01EX1NldFF1ZXN0RmlsdGVy",
            "Q21kEIwIEhoKFUNNRF9DbG9zZVN0YXJHdWlkZUNtZBCNCBIVChBDTURfU2hv",
            "d1F1ZXN0Q21kEI4IEhwKF0NNRF9TZW5kU2hvd1N0YXJJbmZvQ21kEI8IEhsK",
            "FkNNRF9TZW5kUXVlc3ROb2Rlc0RhdGEQkAgSHgoZQ01EX0NsaWVudE5vZGVD",
            "YWxsYmFja0NtZBCRCBIYChNDTURfUXVlc3RGaW5pc2hEYXRhEJIIEhoKFUNN",
            "RF9TZXRVc2VyQ2FuTW92ZUNtZBCTCBIaChVDTURfQ2hhbmdlV1hLSkF1cmFD",
            "bWQQlQgSHQoYQ01EX0NsaWVudFN0b3J5Q2hvb3NlQ21kEJYIEh0KGENNRF9T",
            "eW5jUXVlc3RQcm9ncmVzc0NtZBCXCBIdChhDTURfU0NFTkVfVVNFUl9RVUVT",
            "VF9FTkQQrwkSHQoYQ01EX1NDRU5FX1VTRVJfTUFQX1NUQVJUELAJEhMKDkNN",
            "RF9BZGRNYXBJdGVtELEJEhMKDkNNRF9QaWNrdXBJdGVtELIJEhQKD0NNRF9B",
            "ZGRNYXBFbnRyeRC0CRIWChFDTURfQWRkTWFwTWlzc2lsZRC1CRITCg5DTURf",
            "QWRkTWFwVHJhcBC2CRIXChJDTURfRXhpdFBvaW50U3RhdGUQtwkSEgoNQ01E",
            "X01hcENtZEVuZBC4CRIaChVDTURfTnBjU2VhcmNoUmFuZ2VDbWQQuQkSHQoY",
            "Q01EX05wY0ZlYXR1cmVzVXBkYXRlQ21kELoJEhcKEkNNRF9OcGNOaW5lU3lu",
            "Y0NtZBC7CRIYChNDTURfSXRlbU5pbmVTeW5jQ21kELwJEhkKFENNRF9Hb0Np",
            "dHlHYXRlTWFwQ21kEL4JEhsKFkNNRF9EZWxldGVFbnRyeVVzZXJDbWQQvwkS",
            "GwoWQ01EX1Rlc3RQYXJhYm9sYVBvc0NtZBDACRIWChFDTURfTG9ja1Rhcmdl",
            "dENtZBDBCRIYChNDTURfVW5sb2NrVGFyZ2V0Q21kEMIJEhkKFENNRF9TeW5j",
            "RGlyZWN0aW9uQ21kEMMJEhgKE0NNRF9TeW5jTnBjV2F0Y2hDbWQQxAkSIAob",
            "Q01EX1N5bmNOcGNWaXNpYmxlU3RhdHVzQ21kEMUJEhkKFENNRF9CbG9ja1Nj",
            "ZW5lTWFwQ21kEMYJEh4KGUNNRF9TeW5jTnBjUHJpdmF0ZURhdGFDbWQQyAkS",
            "FgoRQ01EX05wY1BsYXlEaWFsb2cQyQkSFwoSQ01EX1NoYWtlU2NyZWVuQ21k",
            "EMoJEhUKEENNRF9Nb3ZlU3RhdGVDbWQQzAkSFQoQQ01EX0xlYXZlQ29weUNt",
            "ZBDNCRIdChhDTURfVXBkYXRlUmVwYWlyT2JqU3RhdGUQzwkSGQoUQ01EX0Fj",
            "Y2VwdFJlcGFpclRhc2sQ0AkSHQoYQ01EX1NlbmRFZmZlY3RDbG9zZWRUeXBl",
            "ENEJEhoKFUNNRF9Cb3hDaG9pY2VGdW5jdGlvbhDSCRIZChRDTURfU2VydmVy",
            "UG9zVGVzdENtZBDTCRIeChlDTURfRW50ZXJSYWlkU2NlbmVCeVN0YWdlENUJ",
            "EhgKE0NNRF9TZW5kQm94SW5mb0xpc3QQ1gkSGQoUQ01EX1NlbmRCb3NzRW50",
            "ZXJNYXAQ1wkSJAofQ01EX0FkZFBhcnRuZXJFeHBGcm9tRXhwUG9vbENtZBDY",
            "CRIaChVDTURfUGxheUl0ZW1BbmltYXRpb24Q2QkSGAoTQ01EX1dYS0pMZWF2",
            "ZU1hcENtZBDaCRIfChpDTURfU2VydmVyU2VjdG9yUG9zVGVzdENtZBDbCRIY",
            "ChNDTURfU2V0Q29sbGlzaW9uQ21kENwJEh0KGENNRF9UcmlnZ2VyUGVyY2Vw",
            "dGlvbkNtZBDdCRIjCh5DTURfU3luY1N0YWdlT2JqZWN0QmVoYXZpb3JDbWQQ",
            "3gkSGwoWQ01EX1NlcnZlclN3ZWVwVGVzdENtZBDfCRIkCh9DTURfU3luY0Js",
            "dWVwcmludFBlcmZvcm1hbmNlQ21kEOAJEhwKF0NNRF9TZXJ2ZXJCb3hQb3NU",
            "ZXN0Q21kEOEJEiAKG0NNRF9TZXJ2ZXJDYXBzdWxlUG9zVGVzdENtZBDiCRIe",
            "ChlDTURfU2VydmVyQXJyb3dQb3NUZXN0Q21kEOMJEh8KGkNNRF9TZXJ2ZXJT",
            "cGhlcmVQb3NUZXN0Q21kEOQJEhEKDENNRF9TeW5jVGltZRD2ChIbChZDTURf",
            "U0NFTkVfVVNFUl9NQVBfRU5EEPcKEiEKHENNRF9TQ0VORV9VU0VSX1BBUlRO",
            "RVJfU1RBUlQQ+AoSFwoSQ01EX1BhcnRuZXJMaXN0Q21kEPkKEhYKEUNNRF9B",
            "ZGRGaWdodGVyQ21kEPoKEhYKEUNNRF9EZWxGaWdodGVyQ21kEPsKEh4KGUNN",
            "RF9TdGFyVXBncmFkZVBhcnRuZXJDbWQQ/AoSGAoTQ01EX0ZpZ2h0ZXJMZXZl",
            "bENtZBD9ChIWChFDTURfRmlnaHRlckV4cENtZBD+ChIXChJDTURfRmlnaHRl",
            "ckF0dHJDbWQQ/woSGAoTQ01EX0ZpZ2h0ZXJTa2lsbENtZBCACxIfChpDTURf",
            "RmlnaHRlclNraWxsTGV2ZWxVcENtZBCBCxIjCh5DTURfRmlnaHRlclNraWxs",
            "UG9zaXRpb25TZXRDbWQQggsSJQogQ01EX0ZpZ2h0ZXJTa2lsbFBvaW50U3lu",
            "Y0luZm9DbWQQgwsSHwoaQ01EX1NDRU5FX1VTRVJfUEFSVE5FUl9FTkQQvwwS",
            "HgoZQ01EX1NDRU5FX1VTRVJfSVRFTV9TVEFSVBDgEhIbChZDTURfU2VuZFBh",
            "Y2thZ2VMaXN0Q21kEOESEhYKEUNNRF9QYWNrYWdlVXBkYXRlEOISEhYKEUNN",
            "RF9Ccm93c2VQYWNrYWdlEOMSEhwKF0NNRF9FcXVpcFBhY2thZ2VPcGVyQ21k",
            "EOUSEhAKC0NNRF9JdGVtVXNlEOYSEhQKD0NNRF9JdGVtU2hvd0NtZBDnEhIf",
            "ChpDTURfUmV0RXF1aXBQYWNrYWdlT3BlckNtZBDoEhIRCgxDTURfTW9uZXlD",
            "bWQQ6RISFwoSQ01EX01vbmV5VXBkYXRlQ21kEOoSEhkKFENNRF9FcXVpcFN0",
            "cmVuZ3RoQ21kEOsSEhwKF0NNRF9FcXVpcFVwZ3JhZGVTdGFyQ21kEOwSEhwK",
            "F0NNRF9TQ0VORV9VU0VSX0lURU1fRU5EEKcUEh8KGkNNRF9TQ0VORV9VU0VS",
            "X1NUQUdFX1NUQVJUEPAVEhQKD0NNRF9BZGRTdGFnZUNtZBDxFRIUCg9DTURf",
            "RGVsU3RhZ2VDbWQQ8hUSFwoSQ01EX1VwZGF0ZVN0YWdlQ21kEPMVEhoKFUNN",
            "RF9TdGFnZUNvdW50RG93bkNtZBD0FRIaChVDTURfVXBkYXRlVmFyU3RhZ2VD",
            "bWQQ9RUSHQoYQ01EX1NDRU5FX1VTRVJfU1RBR0VfRU5EENMWEh4KGUNNRF9T",
            "Q0VORV9VU0VSX0NIQVRfU1RBUlQQ1BYSHwoaQ01EX0NoYXRNc2dDbGllbnRU",
            "b0dhdGVDbWQQ1RYSHwoaQ01EX0NoYXRNc2dHYXRlVG9DbGllbnRDbWQQ1hYS",
            "HAoXQ01EX1NDRU5FX1VTRVJfQ0hBVF9FTkQQtxcSGwoVQ01EX1JFQ09SRF9E",
            "QVRBX1NUQVJUEMC4AhIeChhDTURfTm90aWZ5TG9naW5SZWNvcmRDbWQQwbgC",
            "EhsKFUNNRF9Vc2VyRGF0YVJlY29yZENtZBDCuAISIgocQ01EX0VyclVzZXJD",
            "aGFyQmFzZVJlY29yZENtZBDDuAISGAoSQ01EX011c2ljVXBkYXRlQ21kEMS4",
            "AhIfChlDTURfTG9hZEx1YVNjZW5lUmVjb3JkQ21kEMW4AhIbChVDTURfUHV0",
            "U3RvcmVSZWNvcmRDbWQQxrgCEhsKFUNNRF9PZmZTdG9yZVJlY29yZENtZBDH",
            "uAISHQoXQ01EX0l0ZW1Nb2RpZnlSZWNvcmRDbWQQyLgCEiIKHENNRF9DaGFu",
            "Z2VBdXRob3JpemVSZWNvcmRDbWQQybgCEiIKHENNRF9HdWlsZE11c2ljUXVl",
            "cnlSZWNvcmRDbWQQyrgCEh0KF0NNRF9HdWlsZE11c2ljVXBkYXRlQ21kEMu4",
            "AhIjCh1DTURfR3VpbGRNdXNpY0RlbGV0ZVJlY29yZENtZBDMuAISHwoZQ01E",
            "X0RlbFBhdGNoQ2hhclJlY29yZENtZBDNuAISGwoVQ01EX0NoYXRTYXZlUmVj",
            "b3JkQ21kEM64AhIcChZDTURfUXVlcnlDaGF0UmVjb3JkQ21kEM+4AhIiChxD",
            "TURfVXNlclJlbmFtZVF1ZXJ5UmVjb3JkQ21kENC4AhIjCh1DTURfVXNlclJl",
            "bmFtZVJlc3VsdFJlY29yZENtZBDRuAISIQobQ01EX1Byb2Zlc3Npb25TYXZl",
            "UmVjb3JkQ21kENS4AhIiChxDTURfUHJvZmVzc2lvblF1ZXJ5UmVjb3JkQ21k",
            "ENW4AhIdChdDTURfU2V0UHViRGF0YVJlY29yZENtZBDWuAISHQoXQ01EX0dl",
            "dFB1YkRhdGFSZWNvcmRDbWQQ17gCEiAKGkNNRF9SZXRTZXRQdWJEYXRhUmVj",
            "b3JkQ21kENi4AhIgChpDTURfUmV0R2V0UHViRGF0YVJlY29yZENtZBDZuAIS",
            "HgoYQ01EX1JldFNhdmVEYXRhUmVjb3JkQ21kENq4AhIZChNDTURfUkVDT1JE",
            "X0RBVEFfRU5EEIe6AhIXChFDTURfU0VTU0lPTl9TVEFSVBDQuwISGwoVQ01E",
            "X0xvYWRMdWFTZXNzaW9uQ21kENq7AhIdChdDTURfRXhlY0dNQ21kU2Vzc2lv",
            "bkNtZBDbuwISDwoJQ01EX0V2ZW50EOK7AhIYChJDTURfQ2hhdE1zZ1Nlc3Np",
            "b24Q47sCEhgKEkNNRF9TZXRHbG9iYWxEYWlseRDkuwISFgoQQ01EX1JlZnJl",
            "c2hRdWVzdBDluwISHwoZQ01EX05vdGlmeUxvZ2luU2Vzc2lvbkNtZBDruwIS",
            "JQofQ01EX0NoYW5nZVNjZW5lU2luZ2xlU2Vzc2lvbkNtZBDtuwISHwoZQ01E",
            "X0ZvcndhcmRVc2VyU2Vzc2lvbkNtZBDwuwISJwohQ01EX0ZvcndhcmRVc2Vy",
            "U2NlbmVTdnJTZXNzaW9uQ21kEPO7AhIcChZDTURfU3luY0Rvam9TZXNzaW9u",
            "Q21kEPW7AhIaChRDTURfQ2hhcmdlU2Vzc2lvbkNtZBD2uwISFwoRQ01EX0dh",
            "Z1Nlc3Npb25DbWQQ97sCEhgKEkNNRF9Mb2NrU2Vzc2lvbkNtZBD4uwISIgoc",
            "Q01EX0FjdGl2aXR5U3RhdHVzU2Vzc2lvbkNtZBD9uwISIQobQ01EX0Zvcndh",
            "cmRSZWdpb25TZXNzaW9uQ21kEP+7AhIiChxDTURfV2FudGVkSW5mb1N5bmNT",
            "ZXNzaW9uQ21kEIK8AhIjCh1DTURfUXVlcnlab25lU3RhdHVzU2Vzc2lvbkNt",
            "ZBCDvAISHwoZQ01EX0dldFRyYWRlTG9nU2Vzc2lvbkNtZBCFvAISIQobQ01E",
            "X0F1dGhvcml6ZUluZm9TZXNzaW9uQ21kEIe8AhIdChdDTURfRGVsZXRlUHdk",
            "U2Vzc2lvbkNtZBCJvAISIgocQ01EX0FkZE9mZmxpbmVJdGVtU2Vzc2lvbkNt",
            "ZBCNvAISJwohQ01EX0dsb2JhbEFjdGl2aXR5U3RhcnRTZXNzaW9uQ21kEJW8",
            "AhImCiBDTURfR2xvYmFsQWN0aXZpdHlTdG9wU2Vzc2lvbkNtZBCWvAISIgoc",
            "Q01EX05vdGlmeUFjdGl2aXR5U2Vzc2lvbkNtZBCZvAISIgocQ01EX1N5bmNX",
            "b3JsZExldmVsU2Vzc2lvbkNtZBCcvAISJAoeQ01EX1NlbmRMdWFFcnJvcklu",
            "Zm9TZXNzaW9uQ21kEJ+8AhIaChRDTURfUlBDU2NyaXB0Q2FsbENtZBCgvAIS",
            "JAoeQ01EX1NjZW5lU2VydmVyQ29uZmlnUmVsb2FkQ21kEKK8AhIhChtDTURf",
            "VXNlclJlY29ubmVjdFNlc3Npb25DbWQQo7wCEiEKG0NNRF9TZXROZXdDaGFy",
            "TWFwU2Vzc2lvbkNtZBCkvAISHwoZQ01EX0ZvcndhcmRTY2VuZVNlcnZlckNt",
            "ZBClvAISFQoPQ01EX1NFU1NJT05fRU5EEJe9AhIXChFDTURfR01UT09MU19T",
            "VEFSVBCYvQISEwoNQ01EX0V4ZWNHTUNtZBCZvQISFgoQQ01EX1JldEV4ZWNH",
            "TUNtZBCavQISFgoQQ01EX1Nlc3Npb25HTUNtZBCbvQISFQoPQ01EX0dNVE9P",
            "TFNfRU5EEN++AhITCg1DTURfTE9HX1NUQVJUEOC+AhIVCg9DTURfTG9naW5M",
            "b2dDbWQQ4b4CEhcKEUNNRF9BY2NvdW50TG9nQ21kEOK+AhIWChBDTURfQ3Jl",
            "YXRlTG9nQ21kEOO+AhIaChRDTURfQ2hhbmdlRmxhZ0xvZ0NtZBDkvgISFgoQ",
            "Q01EX0NoYXJnZUxvZ0NtZBDlvgISFQoPQ01EX0V2ZW50TG9nQ21kEOa+AhIW",
            "ChBDTURfSW5jb21lTG9nQ21kEOe+AhIXChFDTURfQ29uc3VtZUxvZ0NtZBDo",
            "vgISFAoOQ01EX0l0ZW1Mb2dDbWQQ6b4CEhUKD0NNRF9Qcm9wc0xvZ0NtZBDq",
            "vgISGwoVQ01EX1RyYW5zYWN0aW9uTG9nQ21kEOu+AhIUCg5DTURfQ2hhdExv",
            "Z0NtZBDsvgISFQoPQ01EX0xldmVsTG9nQ21kEO2+AhIWChBDTURfT25saW5l",
            "TG9nQ21kEO6+AhIaChRDTURfQ2hlY2twb2ludExvZ0NtZBDvvgISFAoOQ01E",
            "X1JhbmtMb2dDbWQQ8L4CEhYKEENNRF9DaGFuZ2VMb2dDbWQQ8r4CEhUKD0NN",
            "RF9FcXVpcExvZ0NtZBDzvgISFAoOQ01EX0NhcmRMb2dDbWQQ9L4CEhcKEUNN",
            "RF9FcXVpcFVwTG9nQ21kEPW+AhIWChBDTURfU29jYWlsTG9nQ21kEPa+AhIV",
            "Cg9DTURfUXVlc3RMb2dDbWQQ974CEhYKEENNRF9NYW51YWxMb2dDbWQQ+L4C",
            "EhgKEkNNRF9Db21wbGV0ZUxvZ0NtZBD5vgISGAoSQ01EX0l0ZW1PcGVyTG9n",
            "Q21kEPu+AhIUCg5DTURfS2lsbExvZ0NtZBD8vgISFgoQQ01EX1Jld2FyZExv",
            "Z0NtZBD9vgISFAoOQ01EX01haWxMb2dDbWQQ/r4CEhQKDkNNRF9Eb2pvTG9n",
            "Q21kEP++AhIXChFDTURfRW5jaGFudExvZ0NtZBCAvwISGQoTQ01EX0d1aWxk",
            "UHJheUxvZ0NtZBCBvwISGAoSQ01EX1VzZVNraWxsTG9nQ21kEIK/AhIWChBD",
            "TURfQWN0aXZlTG9nQ21kEIO/AhIVCg9DTURfVHJhZGVMb2dDbWQQhL8CEhoK",
            "FENNRF9EZWxldGVDaGFyTG9nQ21kEIW/AhIXChFDTURfQ29tcG9zZUxvZ0Nt",
            "ZBCGvwISGAoSQ01EX0p1bXB6b25lTG9nQ21kEIe/AhIUCg5DTURfVGVhbUxv",
            "Z0NtZBCIvwISIAoaQ01EX1RyYWRlQWRqdXN0UHJpY2VMb2dDbWQQib8CEhoK",
            "FENNRF9UcmFkZVByaWNlTG9nQ21kEIq/AhIbChVDTURfVHJhZGVVbnRha2VM",
            "b2dDbWQQjb8CEhwKFkNNRF9JbmFjdGl2ZVVzZXJMb2dDbWQQjr8CEhYKEENN",
            "RF9DcmVkaXRMb2dDbWQQj78CEhkKE0NNRF9UcmFkZUdpdmVMb2dDbWQQkL8C",
            "EhEKC0NNRF9MT0dfRU5EEKfAAhIaChRDTURfR0FURV9TVVBFUl9TVEFSVBCo",
            "wAISHAoWQ01EX0dhdGVUb1N1cGVyVXNlck51bRCpwAISHQoXQ01EX1B1c2hN",
            "c2dHYXRlU3VwZXJDbWQQqsACEh4KGENNRF9BbHRlck1zZ0dhdGVTdXBlckNt",
            "ZBCrwAISIgocQ01EX1B1c2hUeXJhbnREYkdhdGVTdXBlckNtZBCswAISGAoS",
            "Q01EX0dBVEVfU1VQRVJfRU5EEO/BAhIUCg5DTURfU1RBVF9TVEFSVBC4wwIS",
            "FQoPQ01EX1Rlc3RTdGF0Q21kELnDAhIRCgtDTURfU3RhdENtZBC6wwISGwoV",
            "Q01EX1RyYWRlVG9TdGF0TG9nQ21kELvDAhIfChlDTURfS2lsbE1vbnN0ZXJO",
            "dW1TdGF0Q21kELzDAhIcChZDTURfRGF5R2V0WmVueUNvdW50Q21kEL3DAhIW",
            "ChBDTURfU3RhdEN1ckxldmVsEL7DAhIaChRDTURfUmVxV29ybGRMZXZlbENt",
            "ZBC/wwISEgoMQ01EX1NUQVRfRU5EEP/EAhIWChBDTURfTUFUQ0hTX1NUQVJU",
            "EKDLAhIaChRDTURfTWF0Y2hQbGF5Sm9pbkNtZBChywISGwoVQ01EX01hdGNo",
            "UGxheUxlYXZlQ21kEKLLAhIdChdDTURfUmV0TWF0Y2hQbGF5Sm9pbkNtZBCj",
            "ywISHgoYQ01EX1JldE1hdGNoUGxheUxlYXZlQ21kEKTLAhIZChNDTURfTWF0",
            "Y2hTdWNjZXNzQ21kEKXLAhIUCg5DTURfTUFUQ0hTX0VORBDnzAISFwoRQ01E",
            "X0dBVEVXQVlfU1RBUlQQwNECEhwKFkNNRF9Vc2VyRGF0YUdhdGV3YXlDbWQQ",
            "wdECEiIKHENNRF9Gb3J3YXJkVXNlckNtZEdhdGV3YXlDbWQQwtECEiEKG0NN",
            "RF9Gb3J3YXJkVG9Vc2VyR2F0ZXdheUNtZBDD0QISJgogQ01EX0ZvcndhcmRU",
            "b0xvZ2luVXNlckdhdGV3YXlDbWQQxNECEioKJENNRF9Ccm9hZGNhc3RPbmVM",
            "ZXZlbEluZGV4R2F0ZXdheUNtZBDG0QISJAoeQ01EX0FkZE9uZUxldmVsSW5k",
            "ZXhHYXRld2F5Q21kEMfRAhIkCh5DTURfRGVsT25lTGV2ZWxJbmRleEdhdGV3",
            "YXlDbWQQyNECEh0KF0NNRF9DbWRGaWx0ZXJHYXRld2F5Q21kEMnRAhIWChBD",
            "TURfTG9naW5HYXRlQ21kEMrRAhIXChFDTURfTG9nb3V0R2F0ZUNtZBDL0QIS",
            "GgoUQ01EX0xvZ291dFJlZ0dhdGVDbWQQzNECEhsKFUNNRF9DcmVhdGVDaGFy",
            "R2F0ZUNtZBDN0QISHgoYQ01EX1JldENyZWF0ZUNoYXJHYXRlQ21kEM7RAhIY",
            "ChJDTURfRGVsQ2hhckdhdGVDbWQQ0NECEhsKFUNNRF9SZXREZWxDaGFyR2F0",
            "ZUNtZBDR0QISGwoVQ01EX1VzZXJSZW5hbWVHYXRlQ21kENLRAhIiChxDTURf",
            "R2F0ZVVzZXJPbmxpbmVHYXRld2F5Q21kENPRAhImCiBDTURfUmVmcmVzaFNu",
            "YXBzaG90Q2xpZW50VXNlckNtZBDU0QISIQobQ01EX0Rpc2Nvbm5lY3RDbGll",
            "bnRVc2VyQ21kENbRAhIcChZDTURfUmVxU25hcHNob3RHYXRlQ21kENfRAhIc",
            "ChZDTURfUmV0U25hcHNob3RHYXRlQ21kENjRAhIiChxDTURfUmVsb2dpbkRp",
            "c2Nvbm5lY3RHYXRlQ21kENnRAhIgChpDTURfUmVsb2dpbktpY2tVc2VyR2F0",
            "ZUNtZBDa0QISGwoVQ01EX0xvZ2luRXJyb3JHYXRlQ21kENvRAhIbChVDTURf",
            "U2NlbmVVc2VyQ291bnRDbWQQ3NECEh4KGENNRF9DaGFuZ2VTY2VuZVNlcnZl",
            "ckNtZBDd0QISIAoaQ01EX0Nvbm5lY3Rpb25DbG9zZUdhdGVDbWQQ3tECEhUK",
            "D0NNRF9HQVRFV0FZX0VORBCH0wISFgoQQ01EX1NZU1RFTV9TVEFSVBDQ1AIS",
            "HQoXQ01EX1ZlcmlmeUNvbm5TeXN0ZW1DbWQQ0tQCEh0KF0NNRF9TZXJ2ZXJU",
            "aW1lU3lzdGVtQ21kENXUAhIfChlDTURfQ29tbW9uUmVsb2FkU3lzdGVtQ21k",
            "ENfUAhIcChZDTURfUmVsb2FkTG9nQ29uZmlnQ21kENjUAhIUCg5DTURfU1lT",
            "VEVNX0VORBCX1gISHAoWQ01EX0dBVEVXQVlfQ0hBVF9TVEFSVBCY1gISHQoX",
            "Q01EX0dhdGVUb0NoYXRTZXJ2ZXJDbWQQmdYCEh0KF0NNRF9DaGF0U2VydmVy",
            "VG9HYXRlQ21kEJrWAhIcChZDTURfQ2hhdFNlcnZlckVycm9yQ21kEJ3WAhIa",
            "ChRDTURfR0FURVdBWV9DSEFUX0VORBDf1wISDQoHQ01EX01BWBD//wNCB1oF",
            "LjtDbWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cmd.CommandList), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cmd.Nonce), global::Cmd.Nonce.Parser, new[]{ "Timestamp", "Index", "Sign" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cmd.WrapPacket), global::Cmd.WrapPacket.Parser, new[]{ "Cmd", "Content", "Timestamp", "Seq", "Code", "Reconnectreq" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CommandList {
    /// <summary>
    ///  LOGIN_USER_PROTOCMD
    ///  0~199
    /// </summary>
    [pbr::OriginalName("CMD_LOGIN_USER_START")] CmdLoginUserStart = 0,
    [pbr::OriginalName("CMD_ReqLoginUserCmd")] CmdReqLoginUserCmd = 1,
    [pbr::OriginalName("CMD_CreateCharUserCmd")] CmdCreateCharUserCmd = 2,
    [pbr::OriginalName("CMD_SnapShotUserCmd")] CmdSnapShotUserCmd = 3,
    [pbr::OriginalName("CMD_SelectRoleUserCmd")] CmdSelectRoleUserCmd = 5,
    [pbr::OriginalName("CMD_LoginResultUserCmd")] CmdLoginResultUserCmd = 6,
    [pbr::OriginalName("CMD_DeleteCharUserCmd")] CmdDeleteCharUserCmd = 7,
    [pbr::OriginalName("CMD_HeartBeatUserCmd")] CmdHeartBeatUserCmd = 8,
    [pbr::OriginalName("CMD_ServerTimeUserCmd")] CmdServerTimeUserCmd = 9,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_KickParamUserCmd")] CmdKickParamUserCmd = 13,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_CancelDeleteCharUserCmd")] CmdCancelDeleteCharUserCmd = 14,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ClientFrameUserCmd")] CmdClientFrameUserCmd = 15,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_LOGIN_USER_END")] CmdLoginUserEnd = 199,
    /// <summary>
    ///  ERROR_USER_PROTOCMD
    ///  200~399
    /// </summary>
    [pbr::OriginalName("CMD_ERROR_USER_START")] CmdErrorUserStart = 200,
    [pbr::OriginalName("CMD_RegErrUserCmd")] CmdRegErrUserCmd = 201,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_ERROR_USER_END")] CmdErrorUserEnd = 399,
    /// <summary>
    ///  SCENE_USER_PROTOCMD
    ///  400~599
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_START")] CmdSceneUserStart = 400,
    [pbr::OriginalName("CMD_SetUserDataCmd")] CmdSetUserDataCmd = 401,
    [pbr::OriginalName("CMD_SetNineDataCmd")] CmdSetNineDataCmd = 402,
    [pbr::OriginalName("CMD_UserGMCommand")] CmdUserGmcommand = 403,
    [pbr::OriginalName("CMD_BlackSanCmd")] CmdBlackSanCmd = 404,
    [pbr::OriginalName("CMD_BuffEffectUserCmd")] CmdBuffEffectUserCmd = 405,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_UserFaceCmd")] CmdUserFaceCmd = 406,
    [pbr::OriginalName("CMD_AttrsChangeSyncCmd")] CmdAttrsChangeSyncCmd = 408,
    [pbr::OriginalName("CMD_UserAttrChangeShowCmd")] CmdUserAttrChangeShowCmd = 409,
    [pbr::OriginalName("CMD_SummonEffectUserCmd")] CmdSummonEffectUserCmd = 410,
    [pbr::OriginalName("CMD_BattleObjectEffectUserCmd")] CmdBattleObjectEffectUserCmd = 411,
    [pbr::OriginalName("CMD_RedDotCmd")] CmdRedDotCmd = 412,
    [pbr::OriginalName("CMD_RedDotConfirmCmd")] CmdRedDotConfirmCmd = 413,
    [pbr::OriginalName("CMD_ChangeSceneUserCmd")] CmdChangeSceneUserCmd = 415,
    [pbr::OriginalName("CMD_MissileEffectUserCmd")] CmdMissileEffectUserCmd = 416,
    [pbr::OriginalName("CMD_SkillBroadcastUserCmd")] CmdSkillBroadcastUserCmd = 417,
    [pbr::OriginalName("CMD_MoveEffectUserCmd")] CmdMoveEffectUserCmd = 418,
    [pbr::OriginalName("CMD_DamageEffectUserCmd")] CmdDamageEffectUserCmd = 419,
    [pbr::OriginalName("CMD_UpdateSkillRandSeedCmd")] CmdUpdateSkillRandSeedCmd = 420,
    [pbr::OriginalName("CMD_SkillResultUserCmd")] CmdSkillResultUserCmd = 421,
    [pbr::OriginalName("CMD_CDTimeUserCmd")] CmdCdtimeUserCmd = 423,
    [pbr::OriginalName("CMD_ReliveUserCmd")] CmdReliveUserCmd = 424,
    [pbr::OriginalName("CMD_GoToUserCmd")] CmdGoToUserCmd = 425,
    [pbr::OriginalName("CMD_BreakSkillUserCmd")] CmdBreakSkillUserCmd = 426,
    /// <summary>
    ///  暂时未用 
    /// </summary>
    [pbr::OriginalName("CMD_GoToExitPosUserCmd")] CmdGoToExitPosUserCmd = 427,
    [pbr::OriginalName("CMD_SpecialEffectUserCmd")] CmdSpecialEffectUserCmd = 428,
    [pbr::OriginalName("CMD_AnimMoveSyncPosCmd")] CmdAnimMoveSyncPosCmd = 429,
    /// <summary>
    ///  通知Dynamic Move Effect结束
    /// </summary>
    [pbr::OriginalName("CMD_DynamicMoveEffectEndCmd")] CmdDynamicMoveEffectEndCmd = 430,
    [pbr::OriginalName("CMD_CVisitNpcUserCmd")] CmdCvisitNpcUserCmd = 431,
    [pbr::OriginalName("CMD_CStopVisitNpcUserCmd")] CmdCstopVisitNpcUserCmd = 432,
    [pbr::OriginalName("CMD_SShowDialogUserCmd")] CmdSshowDialogUserCmd = 433,
    [pbr::OriginalName("CMD_ChoosePartnerUserCmd")] CmdChoosePartnerUserCmd = 434,
    [pbr::OriginalName("CMD_TeamDataCmd")] CmdTeamDataCmd = 435,
    [pbr::OriginalName("CMD_SetTeamUserCmd")] CmdSetTeamUserCmd = 436,
    [pbr::OriginalName("CMD_UserBuffNineSyncCmd")] CmdUserBuffNineSyncCmd = 437,
    [pbr::OriginalName("CMD_UserActionNineSyncCmd")] CmdUserActionNineSyncCmd = 438,
    [pbr::OriginalName("CMD_NotifyHideCloseUserCmd")] CmdNotifyHideCloseUserCmd = 439,
    [pbr::OriginalName("CMD_UnlockingMenuCmd")] CmdUnlockingMenuCmd = 440,
    [pbr::OriginalName("CMD_UnlockedMenuDataCmd")] CmdUnlockedMenuDataCmd = 441,
    [pbr::OriginalName("CMD_ReqMapLinkUserCmd")] CmdReqMapLinkUserCmd = 442,
    [pbr::OriginalName("CMD_BroadCastMapLinkUserCmd")] CmdBroadCastMapLinkUserCmd = 443,
    [pbr::OriginalName("CMD_SkillReplacePartnerCmd")] CmdSkillReplacePartnerCmd = 444,
    [pbr::OriginalName("CMD_GoMapUserCmd")] CmdGoMapUserCmd = 445,
    [pbr::OriginalName("CMD_UserEffectNineSyncCmd")] CmdUserEffectNineSyncCmd = 446,
    [pbr::OriginalName("CMD_UserExpressionNineSyncCmd")] CmdUserExpressionNineSyncCmd = 447,
    [pbr::OriginalName("CMD_UserSoundNineSyncCmd")] CmdUserSoundNineSyncCmd = 448,
    [pbr::OriginalName("CMD_PlayCGCmd")] CmdPlayCgcmd = 449,
    [pbr::OriginalName("CMD_UserShowBubbleCmd")] CmdUserShowBubbleCmd = 450,
    [pbr::OriginalName("CMD_RetVisitNpcUserCmd")] CmdRetVisitNpcUserCmd = 451,
    [pbr::OriginalName("CMD_RetStopVisitNpcUserCmd")] CmdRetStopVisitNpcUserCmd = 454,
    /// <summary>
    ///  召唤静态物
    /// </summary>
    [pbr::OriginalName("CMD_SkillActorEffectUserCmd")] CmdSkillActorEffectUserCmd = 455,
    [pbr::OriginalName("CMD_UserSpecialActionCmd")] CmdUserSpecialActionCmd = 457,
    [pbr::OriginalName("CMD_AsideUserCmd")] CmdAsideUserCmd = 458,
    [pbr::OriginalName("CMD_SendPartnerSourceCmd")] CmdSendPartnerSourceCmd = 459,
    /// <summary>
    ///  领取学院赠礼
    /// </summary>
    [pbr::OriginalName("CMD_UserCollegeGiftReceiveCmd")] CmdUserCollegeGiftReceiveCmd = 467,
    /// <summary>
    ///  下发学院赠礼状态
    /// </summary>
    [pbr::OriginalName("CMD_UserCollegeGiftInfoCmd")] CmdUserCollegeGiftInfoCmd = 468,
    /// <summary>
    ///  释放非自己控制伙伴的大招
    /// </summary>
    [pbr::OriginalName("CMD_UserUseUniqueSkillCmd")] CmdUserUseUniqueSkillCmd = 480,
    /// <summary>
    ///  播放人物嘴型
    /// </summary>
    [pbr::OriginalName("CMD_UserMouthNineSyncCmd")] CmdUserMouthNineSyncCmd = 485,
    /// <summary>
    ///  天气相关下发
    /// </summary>
    [pbr::OriginalName("CMD_WeatherChange")] CmdWeatherChange = 488,
    /// <summary>
    ///  妄想空间旁白
    /// </summary>
    [pbr::OriginalName("CMD_WXKJAsideUserCmd")] CmdWxkjasideUserCmd = 489,
    /// <summary>
    ///  通用追踪传送(包含修复物)
    /// </summary>
    [pbr::OriginalName("CMD_GoToCommonTraceCmd")] CmdGoToCommonTraceCmd = 490,
    /// <summary>
    ///  通知任务保存数据
    /// </summary>
    [pbr::OriginalName("CMD_UpdateQuestVarCmd")] CmdUpdateQuestVarCmd = 491,
    /// <summary>
    /// 副本模块
    /// </summary>
    [pbr::OriginalName("CMD_RaidWinCmd")] CmdRaidWinCmd = 492,
    /// <summary>
    ///  退出副本
    /// </summary>
    [pbr::OriginalName("CMD_RaidBackCmd")] CmdRaidBackCmd = 493,
    /// <summary>
    ///  抽卡
    /// </summary>
    [pbr::OriginalName("CMD_LotteryCmd")] CmdLotteryCmd = 494,
    /// <summary>
    ///  抽卡结果
    /// </summary>
    [pbr::OriginalName("CMD_SendLotteryResultCmd")] CmdSendLotteryResultCmd = 495,
    /// <summary>
    /// 小地图显示信息
    /// </summary>
    [pbr::OriginalName("CMD_MiniMapsInfoCmd")] CmdMiniMapsInfoCmd = 496,
    /// <summary>
    ///  GM抽卡结果
    /// </summary>
    [pbr::OriginalName("CMD_SendGMLotteryResultCmd")] CmdSendGmlotteryResultCmd = 497,
    /// <summary>
    /// 交互模式
    /// </summary>
    [pbr::OriginalName("CMD_SyncNpcInteractionModeCmd")] CmdSyncNpcInteractionModeCmd = 498,
    [pbr::OriginalName("CMD_SceneRaidResultCmd")] CmdSceneRaidResultCmd = 499,
    /// <summary>
    ///  前端同步给后端 buff信息修改
    /// </summary>
    [pbr::OriginalName("CMD_C2SBuffSyncCmd")] CmdC2SbuffSyncCmd = 500,
    /// <summary>
    ///  同步npc休闲表演列表
    /// </summary>
    [pbr::OriginalName("CMD_SyncActionListCmd")] CmdSyncActionListCmd = 501,
    /// <summary>
    ///  前端感知到玩家进入Npc气泡感知范围
    /// </summary>
    [pbr::OriginalName("CMD_NpcBubblePerceptionCmd")] CmdNpcBubblePerceptionCmd = 502,
    /// <summary>
    ///  展示死亡UI
    /// </summary>
    [pbr::OriginalName("CMD_SyncUserDeadCmd")] CmdSyncUserDeadCmd = 503,
    [pbr::OriginalName("CMD_SyncObjectStatusCmd")] CmdSyncObjectStatusCmd = 511,
    /// <summary>
    /// root motion使用开关同步
    /// </summary>
    [pbr::OriginalName("CMD_RootMotionSwitchCmd")] CmdRootMotionSwitchCmd = 595,
    [pbr::OriginalName("CMD_SetRobotCmd")] CmdSetRobotCmd = 596,
    /// <summary>
    /// 增加弱同步开关同步
    /// </summary>
    [pbr::OriginalName("CMD_WeakSyncSwitchCmd")] CmdWeakSyncSwitchCmd = 597,
    /// <summary>
    /// 增加压测接口返回协议
    /// </summary>
    [pbr::OriginalName("CMD_StressTestResponseCmd")] CmdStressTestResponseCmd = 598,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_END")] CmdSceneUserEnd = 599,
    /// <summary>
    ///  SCENE_USER2_PROTOCMD
    ///  600~799
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER2_START")] CmdSceneUser2Start = 600,
    [pbr::OriginalName("CMD_SysMsg")] CmdSysMsg = 602,
    [pbr::OriginalName("CMD_CExitPosUserCmd")] CmdCexitPosUserCmd = 604,
    [pbr::OriginalName("CMD_CWorldJumpUserCmd")] CmdCworldJumpUserCmd = 605,
    [pbr::OriginalName("CMD_CAskUnlockedMenuListCmd")] CmdCaskUnlockedMenuListCmd = 606,
    [pbr::OriginalName("CMD_SUserDataCmd")] CmdSuserDataCmd = 608,
    /// <summary>
    ///  抱猫或者放下猫
    /// </summary>
    [pbr::OriginalName("CMD_CatHugCmd")] CmdCatHugCmd = 609,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_EffectUserCmd")] CmdEffectUserCmd = 611,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_QueryShopGotItem")] CmdQueryShopGotItem = 623,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_UpdateShopGotItem")] CmdUpdateShopGotItem = 624,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_OpenUI")] CmdOpenUi = 625,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_FollowTransferCmd")] CmdFollowTransferCmd = 627,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_CallNpcFuncCmd")] CmdCallNpcFuncCmd = 628,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ModelShow")] CmdModelShow = 629,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_SoundEffectCmd")] CmdSoundEffectCmd = 630,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ChangeBgmCmd")] CmdChangeBgmCmd = 632,
    [pbr::OriginalName("CMD_GameTimeCmd")] CmdGameTimeCmd = 633,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ShakeScreen")] CmdShakeScreen = 636,
    [pbr::OriginalName("CMD_NpcChangeAngle")] CmdNpcChangeAngle = 639,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_GoToGearUserCmd")] CmdGoToGearUserCmd = 642,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_FollowerUser")] CmdFollowerUser = 644,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_BeFollowUserCmd")] CmdBeFollowUserCmd = 645,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_GotoLaboratoryUserCmd")] CmdGotoLaboratoryUserCmd = 647,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_SceneryUserCmd")] CmdSceneryUserCmd = 648,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_UserAutoHitCmd")] CmdUserAutoHitCmd = 651,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_UploadSceneryPhotoUserCmd")] CmdUploadSceneryPhotoUserCmd = 652,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_DownloadSceneryPhotoUserCmd")] CmdDownloadSceneryPhotoUserCmd = 653,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_BuffForeverCmd")] CmdBuffForeverCmd = 656,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_InviteJoinHandsUserCmd")] CmdInviteJoinHandsUserCmd = 657,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_BreakUpHandsUserCmd")] CmdBreakUpHandsUserCmd = 658,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_HandStatusUserCmd")] CmdHandStatusUserCmd = 659,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_JoinHandsUserCmd")] CmdJoinHandsUserCmd = 665,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ShakeTreeUserCmd")] CmdShakeTreeUserCmd = 674,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_TreeListUserCmd")] CmdTreeListUserCmd = 675,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ItemImageUserNtfUserCmd")] CmdItemImageUserNtfUserCmd = 679,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ChangeNameUserCmd")] CmdChangeNameUserCmd = 681,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_NtfVisibleNpcUserCmd")] CmdNtfVisibleNpcUserCmd = 691,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_UpyunAuthorizationCmd")] CmdUpyunAuthorizationCmd = 692,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_UserRenameCmd")] CmdUserRenameCmd = 693,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_EnterCapraActivityCmd")] CmdEnterCapraActivityCmd = 694,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_BuyZenyCmd")] CmdBuyZenyCmd = 695,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_CallTeamerUserCmd")] CmdCallTeamerUserCmd = 696,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_CallTeamerReplyUserCmd")] CmdCallTeamerReplyUserCmd = 697,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ShowServantUserCmd")] CmdShowServantUserCmd = 704,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ReplaceServantUserCmd")] CmdReplaceServantUserCmd = 705,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ServantService")] CmdServantService = 706,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_RecommendServantUserCmd")] CmdRecommendServantUserCmd = 707,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ReceiveServantUserCmd")] CmdReceiveServantUserCmd = 708,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ServantRewardStatusUserCmd")] CmdServantRewardStatusUserCmd = 709,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_TwinsActionUserCmd")] CmdTwinsActionUserCmd = 711,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_BoothReqUserCmd")] CmdBoothReqUserCmd = 726,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_BoothInfoSyncUserCmd")] CmdBoothInfoSyncUserCmd = 727,
    /// <summary>
    /// S &lt;- C在播放cg途中进行主角坐标切换
    /// </summary>
    [pbr::OriginalName("CMD_ChangeUserPosInRapairCmd")] CmdChangeUserPosInRapairCmd = 728,
    /// <summary>
    ///  C &lt;-> S  获取抽卡池信息
    /// </summary>
    [pbr::OriginalName("CMD_SendLotteryPoolInfoCmd")] CmdSendLotteryPoolInfoCmd = 730,
    /// <summary>
    ///  交互模块 
    /// </summary>
    [pbr::OriginalName("CMD_InteractionWithEntryCmd")] CmdInteractionWithEntryCmd = 731,
    /// <summary>
    /// 交互
    /// </summary>
    [pbr::OriginalName("CMD_InteractionCmd")] CmdInteractionCmd = 732,
    /// <summary>
    ///  拾取
    /// </summary>
    [pbr::OriginalName("CMD_PickUpCmd")] CmdPickUpCmd = 733,
    /// <summary>
    ///  放下
    /// </summary>
    [pbr::OriginalName("CMD_PutDownCmd")] CmdPutDownCmd = 734,
    /// <summary>
    ///  扔
    /// </summary>
    [pbr::OriginalName("CMD_ThrowCmd")] CmdThrowCmd = 735,
    /// <summary>
    ///  弹射
    /// </summary>
    [pbr::OriginalName("CMD_CatapultCmd")] CmdCatapultCmd = 736,
    /// <summary>
    ///  拾取结果
    /// </summary>
    [pbr::OriginalName("CMD_PickUpResultCmd")] CmdPickUpResultCmd = 737,
    /// <summary>
    ///  放下结果
    /// </summary>
    [pbr::OriginalName("CMD_PutDownResultCmd")] CmdPutDownResultCmd = 738,
    /// <summary>
    ///  扔结果
    /// </summary>
    [pbr::OriginalName("CMD_ThrowResultCmd")] CmdThrowResultCmd = 739,
    /// <summary>
    ///  弹射结果
    /// </summary>
    [pbr::OriginalName("CMD_CatapultResultCmd")] CmdCatapultResultCmd = 740,
    /// <summary>
    ///  交互结果
    /// </summary>
    [pbr::OriginalName("CMD_InteractionResultCmd")] CmdInteractionResultCmd = 741,
    /// <summary>
    ///  妄想空间关卡状态
    /// </summary>
    [pbr::OriginalName("CMD_WXKJStagesInfoCmd")] CmdWxkjstagesInfoCmd = 742,
    /// <summary>
    ///  上载具
    /// </summary>
    [pbr::OriginalName("CMD_OnVehicleCmd")] CmdOnVehicleCmd = 744,
    /// <summary>
    ///  上载具返回
    /// </summary>
    [pbr::OriginalName("CMD_OnVehicleResultCmd")] CmdOnVehicleResultCmd = 745,
    /// <summary>
    ///  下载具
    /// </summary>
    [pbr::OriginalName("CMD_OffVehicleCmd")] CmdOffVehicleCmd = 746,
    /// <summary>
    ///  下载具返回
    /// </summary>
    [pbr::OriginalName("CMD_OffVehicleResultCmd")] CmdOffVehicleResultCmd = 747,
    /// <summary>
    ///  通知交互事件
    /// </summary>
    [pbr::OriginalName("CMD_InteractionEventCmd")] CmdInteractionEventCmd = 748,
    /// <summary>
    ///  妄想空间伙伴挑战 C -> S
    /// </summary>
    [pbr::OriginalName("CMD_WXKJChallengeCmd")] CmdWxkjchallengeCmd = 749,
    /// <summary>
    ///  精英修复
    /// </summary>
    [pbr::OriginalName("CMD_EliteRepairCmd")] CmdEliteRepairCmd = 750,
    /// <summary>
    ///  妄想空间材质切换 C &lt;-> S
    /// </summary>
    [pbr::OriginalName("CMD_WXKJSwitchMaterialCmd")] CmdWxkjswitchMaterialCmd = 751,
    /// <summary>
    ///  日常玩法 
    /// </summary>
    [pbr::OriginalName("CMD_DailyActivityCmd")] CmdDailyActivityCmd = 752,
    /// <summary>
    ///  请求日常活动奖励
    /// </summary>
    [pbr::OriginalName("CMD_DailyActivityAwardCmd")] CmdDailyActivityAwardCmd = 753,
    /// <summary>
    ///  请求日常活动全完成奖励
    /// </summary>
    [pbr::OriginalName("CMD_DailyActivityCompleteAwardCmd")] CmdDailyActivityCompleteAwardCmd = 754,
    /// <summary>
    ///  好感度玩法 
    /// </summary>
    [pbr::OriginalName("CMD_FavorabilityCmd")] CmdFavorabilityCmd = 755,
    /// <summary>
    ///  S -> C  发送服务器最后一次收到的协议编号
    /// </summary>
    [pbr::OriginalName("CMD_SendReloginServerReqCmd")] CmdSendReloginServerReqCmd = 756,
    /// <summary>
    ///  天团挑战 
    /// </summary>
    [pbr::OriginalName("CMD_ClubChallengeCGCmd")] CmdClubChallengeCgcmd = 760,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER2_END")] CmdSceneUser2End = 799,
    /// <summary>
    ///  SCENE_USER_SKILL_PROTOCMD
    ///  800~999
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_SKILL_START")] CmdSceneUserSkillStart = 800,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_SKILL_END")] CmdSceneUserSkillEnd = 999,
    /// <summary>
    ///  SCENE_USER_QUEST_PROTOCMD
    ///  1000~1199
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_QUEST_START")] CmdSceneUserQuestStart = 1000,
    [pbr::OriginalName("CMD_ClientEventCmd")] CmdClientEventCmd = 1022,
    [pbr::OriginalName("CMD_ClientEventCallbackCmd")] CmdClientEventCallbackCmd = 1023,
    [pbr::OriginalName("CMD_QuestListCmd")] CmdQuestListCmd = 1024,
    [pbr::OriginalName("CMD_AddQuestCmd")] CmdAddQuestCmd = 1025,
    [pbr::OriginalName("CMD_DelQuestCmd")] CmdDelQuestCmd = 1026,
    [pbr::OriginalName("CMD_UpdateQuestCmd")] CmdUpdateQuestCmd = 1027,
    [pbr::OriginalName("CMD_UpdateVarQuestCmd")] CmdUpdateVarQuestCmd = 1028,
    [pbr::OriginalName("CMD_AcceptableQuestsCmd")] CmdAcceptableQuestsCmd = 1029,
    [pbr::OriginalName("CMD_ShowRewardOnDialog")] CmdShowRewardOnDialog = 1030,
    [pbr::OriginalName("CMD_RewardCommonCmd")] CmdRewardCommonCmd = 1031,
    [pbr::OriginalName("CMD_GetRewardQuestCmd")] CmdGetRewardQuestCmd = 1032,
    [pbr::OriginalName("CMD_QuestListDialogCmd")] CmdQuestListDialogCmd = 1033,
    [pbr::OriginalName("CMD_RetQuestListDialogCmd")] CmdRetQuestListDialogCmd = 1034,
    [pbr::OriginalName("CMD_QuestPositionTraceListCmd")] CmdQuestPositionTraceListCmd = 1035,
    [pbr::OriginalName("CMD_SetQuestFilterCmd")] CmdSetQuestFilterCmd = 1036,
    [pbr::OriginalName("CMD_CloseStarGuideCmd")] CmdCloseStarGuideCmd = 1037,
    [pbr::OriginalName("CMD_ShowQuestCmd")] CmdShowQuestCmd = 1038,
    [pbr::OriginalName("CMD_SendShowStarInfoCmd")] CmdSendShowStarInfoCmd = 1039,
    [pbr::OriginalName("CMD_SendQuestNodesData")] CmdSendQuestNodesData = 1040,
    [pbr::OriginalName("CMD_ClientNodeCallbackCmd")] CmdClientNodeCallbackCmd = 1041,
    [pbr::OriginalName("CMD_QuestFinishData")] CmdQuestFinishData = 1042,
    [pbr::OriginalName("CMD_SetUserCanMoveCmd")] CmdSetUserCanMoveCmd = 1043,
    [pbr::OriginalName("CMD_ChangeWXKJAuraCmd")] CmdChangeWxkjauraCmd = 1045,
    [pbr::OriginalName("CMD_ClientStoryChooseCmd")] CmdClientStoryChooseCmd = 1046,
    [pbr::OriginalName("CMD_SyncQuestProgressCmd")] CmdSyncQuestProgressCmd = 1047,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_QUEST_END")] CmdSceneUserQuestEnd = 1199,
    /// <summary>
    ///  SCENE_USER_MAP_PROTOCMD
    ///  1200~1399
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_MAP_START")] CmdSceneUserMapStart = 1200,
    [pbr::OriginalName("CMD_AddMapItem")] CmdAddMapItem = 1201,
    [pbr::OriginalName("CMD_PickupItem")] CmdPickupItem = 1202,
    [pbr::OriginalName("CMD_AddMapEntry")] CmdAddMapEntry = 1204,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_AddMapMissile")] CmdAddMapMissile = 1205,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_AddMapTrap")] CmdAddMapTrap = 1206,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_ExitPointState")] CmdExitPointState = 1207,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_MapCmdEnd")] CmdMapCmdEnd = 1208,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_NpcSearchRangeCmd")] CmdNpcSearchRangeCmd = 1209,
    /// <summary>
    ///  NPC特性更新,S->C
    /// </summary>
    [pbr::OriginalName("CMD_NpcFeaturesUpdateCmd")] CmdNpcFeaturesUpdateCmd = 1210,
    /// <summary>
    /// Npc九屏属性刷新
    /// </summary>
    [pbr::OriginalName("CMD_NpcNineSyncCmd")] CmdNpcNineSyncCmd = 1211,
    /// <summary>
    /// Item九屏属性刷新
    /// </summary>
    [pbr::OriginalName("CMD_ItemNineSyncCmd")] CmdItemNineSyncCmd = 1212,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_GoCityGateMapCmd")] CmdGoCityGateMapCmd = 1214,
    [pbr::OriginalName("CMD_DeleteEntryUserCmd")] CmdDeleteEntryUserCmd = 1215,
    [pbr::OriginalName("CMD_TestParabolaPosCmd")] CmdTestParabolaPosCmd = 1216,
    [pbr::OriginalName("CMD_LockTargetCmd")] CmdLockTargetCmd = 1217,
    [pbr::OriginalName("CMD_UnlockTargetCmd")] CmdUnlockTargetCmd = 1218,
    [pbr::OriginalName("CMD_SyncDirectionCmd")] CmdSyncDirectionCmd = 1219,
    [pbr::OriginalName("CMD_SyncNpcWatchCmd")] CmdSyncNpcWatchCmd = 1220,
    [pbr::OriginalName("CMD_SyncNpcVisibleStatusCmd")] CmdSyncNpcVisibleStatusCmd = 1221,
    [pbr::OriginalName("CMD_BlockSceneMapCmd")] CmdBlockSceneMapCmd = 1222,
    [pbr::OriginalName("CMD_SyncNpcPrivateDataCmd")] CmdSyncNpcPrivateDataCmd = 1224,
    [pbr::OriginalName("CMD_NpcPlayDialog")] CmdNpcPlayDialog = 1225,
    [pbr::OriginalName("CMD_ShakeScreenCmd")] CmdShakeScreenCmd = 1226,
    [pbr::OriginalName("CMD_MoveStateCmd")] CmdMoveStateCmd = 1228,
    [pbr::OriginalName("CMD_LeaveCopyCmd")] CmdLeaveCopyCmd = 1229,
    [pbr::OriginalName("CMD_UpdateRepairObjState")] CmdUpdateRepairObjState = 1231,
    [pbr::OriginalName("CMD_AcceptRepairTask")] CmdAcceptRepairTask = 1232,
    [pbr::OriginalName("CMD_SendEffectClosedType")] CmdSendEffectClosedType = 1233,
    [pbr::OriginalName("CMD_BoxChoiceFunction")] CmdBoxChoiceFunction = 1234,
    [pbr::OriginalName("CMD_ServerPosTestCmd")] CmdServerPosTestCmd = 1235,
    /// <summary>
    ///  C&lt;->S
    /// </summary>
    [pbr::OriginalName("CMD_EnterRaidSceneByStage")] CmdEnterRaidSceneByStage = 1237,
    /// <summary>
    ///  S->C
    /// </summary>
    [pbr::OriginalName("CMD_SendBoxInfoList")] CmdSendBoxInfoList = 1238,
    /// <summary>
    /// S->C
    /// </summary>
    [pbr::OriginalName("CMD_SendBossEnterMap")] CmdSendBossEnterMap = 1239,
    /// <summary>
    /// C&lt;->S
    /// </summary>
    [pbr::OriginalName("CMD_AddPartnerExpFromExpPoolCmd")] CmdAddPartnerExpFromExpPoolCmd = 1240,
    /// <summary>
    /// C&lt;-S
    /// </summary>
    [pbr::OriginalName("CMD_PlayItemAnimation")] CmdPlayItemAnimation = 1241,
    /// <summary>
    /// C&lt;-S
    /// </summary>
    [pbr::OriginalName("CMD_WXKJLeaveMapCmd")] CmdWxkjleaveMapCmd = 1242,
    [pbr::OriginalName("CMD_ServerSectorPosTestCmd")] CmdServerSectorPosTestCmd = 1243,
    [pbr::OriginalName("CMD_SetCollisionCmd")] CmdSetCollisionCmd = 1244,
    /// <summary>
    ///  触发感知区域
    /// </summary>
    [pbr::OriginalName("CMD_TriggerPerceptionCmd")] CmdTriggerPerceptionCmd = 1245,
    /// <summary>
    ///  客户端之间的行为表现同步，服务器仅负责转发,C->S->C
    /// </summary>
    [pbr::OriginalName("CMD_SyncStageObjectBehaviorCmd")] CmdSyncStageObjectBehaviorCmd = 1246,
    [pbr::OriginalName("CMD_ServerSweepTestCmd")] CmdServerSweepTestCmd = 1247,
    /// <summary>
    ///  客户端之间的蓝图表现同步，服务器仅负责转发,C->S->C
    /// </summary>
    [pbr::OriginalName("CMD_SyncBlueprintPerformanceCmd")] CmdSyncBlueprintPerformanceCmd = 1248,
    [pbr::OriginalName("CMD_ServerBoxPosTestCmd")] CmdServerBoxPosTestCmd = 1249,
    [pbr::OriginalName("CMD_ServerCapsulePosTestCmd")] CmdServerCapsulePosTestCmd = 1250,
    [pbr::OriginalName("CMD_ServerArrowPosTestCmd")] CmdServerArrowPosTestCmd = 1251,
    [pbr::OriginalName("CMD_ServerSpherePosTestCmd")] CmdServerSpherePosTestCmd = 1252,
    [pbr::OriginalName("CMD_SyncTime")] CmdSyncTime = 1398,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_MAP_END")] CmdSceneUserMapEnd = 1399,
    /// <summary>
    ///  SCENE_USER_PARTNER_PROTOCMD
    ///  1400~1599
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_PARTNER_START")] CmdSceneUserPartnerStart = 1400,
    [pbr::OriginalName("CMD_PartnerListCmd")] CmdPartnerListCmd = 1401,
    [pbr::OriginalName("CMD_AddFighterCmd")] CmdAddFighterCmd = 1402,
    [pbr::OriginalName("CMD_DelFighterCmd")] CmdDelFighterCmd = 1403,
    [pbr::OriginalName("CMD_StarUpgradePartnerCmd")] CmdStarUpgradePartnerCmd = 1404,
    [pbr::OriginalName("CMD_FighterLevelCmd")] CmdFighterLevelCmd = 1405,
    [pbr::OriginalName("CMD_FighterExpCmd")] CmdFighterExpCmd = 1406,
    [pbr::OriginalName("CMD_FighterAttrCmd")] CmdFighterAttrCmd = 1407,
    [pbr::OriginalName("CMD_FighterSkillCmd")] CmdFighterSkillCmd = 1408,
    /// <summary>
    ///  伙伴技能升级
    /// </summary>
    [pbr::OriginalName("CMD_FighterSkillLevelUpCmd")] CmdFighterSkillLevelUpCmd = 1409,
    /// <summary>
    ///  伙伴技能槽位设置
    /// </summary>
    [pbr::OriginalName("CMD_FighterSkillPositionSetCmd")] CmdFighterSkillPositionSetCmd = 1410,
    /// <summary>
    ///  同步技能点
    /// </summary>
    [pbr::OriginalName("CMD_FighterSkillPointSyncInfoCmd")] CmdFighterSkillPointSyncInfoCmd = 1411,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_PARTNER_END")] CmdSceneUserPartnerEnd = 1599,
    /// <summary>
    ///  SCENE_USER_ITEM_PROTOCMD
    ///  2400~2599
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_ITEM_START")] CmdSceneUserItemStart = 2400,
    [pbr::OriginalName("CMD_SendPackageListCmd")] CmdSendPackageListCmd = 2401,
    [pbr::OriginalName("CMD_PackageUpdate")] CmdPackageUpdate = 2402,
    /// <summary>
    ///  暂时未用
    /// </summary>
    [pbr::OriginalName("CMD_BrowsePackage")] CmdBrowsePackage = 2403,
    [pbr::OriginalName("CMD_EquipPackageOperCmd")] CmdEquipPackageOperCmd = 2405,
    [pbr::OriginalName("CMD_ItemUse")] CmdItemUse = 2406,
    [pbr::OriginalName("CMD_ItemShowCmd")] CmdItemShowCmd = 2407,
    [pbr::OriginalName("CMD_RetEquipPackageOperCmd")] CmdRetEquipPackageOperCmd = 2408,
    [pbr::OriginalName("CMD_MoneyCmd")] CmdMoneyCmd = 2409,
    [pbr::OriginalName("CMD_MoneyUpdateCmd")] CmdMoneyUpdateCmd = 2410,
    [pbr::OriginalName("CMD_EquipStrengthCmd")] CmdEquipStrengthCmd = 2411,
    [pbr::OriginalName("CMD_EquipUpgradeStarCmd")] CmdEquipUpgradeStarCmd = 2412,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_ITEM_END")] CmdSceneUserItemEnd = 2599,
    /// <summary>
    ///  SCENE_USER_STAGE_PROTOCMD
    ///  2800~2899
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_STAGE_START")] CmdSceneUserStageStart = 2800,
    [pbr::OriginalName("CMD_AddStageCmd")] CmdAddStageCmd = 2801,
    [pbr::OriginalName("CMD_DelStageCmd")] CmdDelStageCmd = 2802,
    [pbr::OriginalName("CMD_UpdateStageCmd")] CmdUpdateStageCmd = 2803,
    /// <summary>
    ///  关卡倒计时信息
    /// </summary>
    [pbr::OriginalName("CMD_StageCountDownCmd")] CmdStageCountDownCmd = 2804,
    [pbr::OriginalName("CMD_UpdateVarStageCmd")] CmdUpdateVarStageCmd = 2805,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_STAGE_END")] CmdSceneUserStageEnd = 2899,
    /// <summary>
    ///  2900~2999
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_CHAT_START")] CmdSceneUserChatStart = 2900,
    /// <summary>
    ///  接收Client的聊天消息
    /// </summary>
    [pbr::OriginalName("CMD_ChatMsgClientToGateCmd")] CmdChatMsgClientToGateCmd = 2901,
    /// <summary>
    ///  Gate转发来自ChatServer的消息到客户端
    /// </summary>
    [pbr::OriginalName("CMD_ChatMsgGateToClientCmd")] CmdChatMsgGateToClientCmd = 2902,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SCENE_USER_CHAT_END")] CmdSceneUserChatEnd = 2999,
    /// <summary>
    ///  Server Only(40000以后)
    ///  RECORD_DATA_PROTOCMD
    ///  40000~40199
    /// </summary>
    [pbr::OriginalName("CMD_RECORD_DATA_START")] CmdRecordDataStart = 40000,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_NotifyLoginRecordCmd")] CmdNotifyLoginRecordCmd = 40001,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_UserDataRecordCmd")] CmdUserDataRecordCmd = 40002,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_ErrUserCharBaseRecordCmd")] CmdErrUserCharBaseRecordCmd = 40003,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_MusicUpdateCmd")] CmdMusicUpdateCmd = 40004,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_LoadLuaSceneRecordCmd")] CmdLoadLuaSceneRecordCmd = 40005,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_PutStoreRecordCmd")] CmdPutStoreRecordCmd = 40006,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_OffStoreRecordCmd")] CmdOffStoreRecordCmd = 40007,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_ItemModifyRecordCmd")] CmdItemModifyRecordCmd = 40008,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_ChangeAuthorizeRecordCmd")] CmdChangeAuthorizeRecordCmd = 40009,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_GuildMusicQueryRecordCmd")] CmdGuildMusicQueryRecordCmd = 40010,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_GuildMusicUpdateCmd")] CmdGuildMusicUpdateCmd = 40011,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_GuildMusicDeleteRecordCmd")] CmdGuildMusicDeleteRecordCmd = 40012,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_DelPatchCharRecordCmd")] CmdDelPatchCharRecordCmd = 40013,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_ChatSaveRecordCmd")] CmdChatSaveRecordCmd = 40014,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_QueryChatRecordCmd")] CmdQueryChatRecordCmd = 40015,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_UserRenameQueryRecordCmd")] CmdUserRenameQueryRecordCmd = 40016,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_UserRenameResultRecordCmd")] CmdUserRenameResultRecordCmd = 40017,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_ProfessionSaveRecordCmd")] CmdProfessionSaveRecordCmd = 40020,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_ProfessionQueryRecordCmd")] CmdProfessionQueryRecordCmd = 40021,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_SetPubDataRecordCmd")] CmdSetPubDataRecordCmd = 40022,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_GetPubDataRecordCmd")] CmdGetPubDataRecordCmd = 40023,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_RetSetPubDataRecordCmd")] CmdRetSetPubDataRecordCmd = 40024,
    /// <summary>
    ///  ServerOnly
    /// </summary>
    [pbr::OriginalName("CMD_RetGetPubDataRecordCmd")] CmdRetGetPubDataRecordCmd = 40025,
    [pbr::OriginalName("CMD_RetSaveDataRecordCmd")] CmdRetSaveDataRecordCmd = 40026,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_RECORD_DATA_END")] CmdRecordDataEnd = 40199,
    /// <summary>
    ///  SESSION_PROTOCMD
    ///  40400~40599
    /// </summary>
    [pbr::OriginalName("CMD_SESSION_START")] CmdSessionStart = 40400,
    [pbr::OriginalName("CMD_LoadLuaSessionCmd")] CmdLoadLuaSessionCmd = 40410,
    [pbr::OriginalName("CMD_ExecGMCmdSessionCmd")] CmdExecGmcmdSessionCmd = 40411,
    [pbr::OriginalName("CMD_Event")] CmdEvent = 40418,
    [pbr::OriginalName("CMD_ChatMsgSession")] CmdChatMsgSession = 40419,
    [pbr::OriginalName("CMD_SetGlobalDaily")] CmdSetGlobalDaily = 40420,
    [pbr::OriginalName("CMD_RefreshQuest")] CmdRefreshQuest = 40421,
    [pbr::OriginalName("CMD_NotifyLoginSessionCmd")] CmdNotifyLoginSessionCmd = 40427,
    [pbr::OriginalName("CMD_ChangeSceneSingleSessionCmd")] CmdChangeSceneSingleSessionCmd = 40429,
    [pbr::OriginalName("CMD_ForwardUserSessionCmd")] CmdForwardUserSessionCmd = 40432,
    [pbr::OriginalName("CMD_ForwardUserSceneSvrSessionCmd")] CmdForwardUserSceneSvrSessionCmd = 40435,
    [pbr::OriginalName("CMD_SyncDojoSessionCmd")] CmdSyncDojoSessionCmd = 40437,
    [pbr::OriginalName("CMD_ChargeSessionCmd")] CmdChargeSessionCmd = 40438,
    [pbr::OriginalName("CMD_GagSessionCmd")] CmdGagSessionCmd = 40439,
    [pbr::OriginalName("CMD_LockSessionCmd")] CmdLockSessionCmd = 40440,
    [pbr::OriginalName("CMD_ActivityStatusSessionCmd")] CmdActivityStatusSessionCmd = 40445,
    [pbr::OriginalName("CMD_ForwardRegionSessionCmd")] CmdForwardRegionSessionCmd = 40447,
    [pbr::OriginalName("CMD_WantedInfoSyncSessionCmd")] CmdWantedInfoSyncSessionCmd = 40450,
    [pbr::OriginalName("CMD_QueryZoneStatusSessionCmd")] CmdQueryZoneStatusSessionCmd = 40451,
    [pbr::OriginalName("CMD_GetTradeLogSessionCmd")] CmdGetTradeLogSessionCmd = 40453,
    [pbr::OriginalName("CMD_AuthorizeInfoSessionCmd")] CmdAuthorizeInfoSessionCmd = 40455,
    [pbr::OriginalName("CMD_DeletePwdSessionCmd")] CmdDeletePwdSessionCmd = 40457,
    [pbr::OriginalName("CMD_AddOfflineItemSessionCmd")] CmdAddOfflineItemSessionCmd = 40461,
    [pbr::OriginalName("CMD_GlobalActivityStartSessionCmd")] CmdGlobalActivityStartSessionCmd = 40469,
    [pbr::OriginalName("CMD_GlobalActivityStopSessionCmd")] CmdGlobalActivityStopSessionCmd = 40470,
    [pbr::OriginalName("CMD_NotifyActivitySessionCmd")] CmdNotifyActivitySessionCmd = 40473,
    [pbr::OriginalName("CMD_SyncWorldLevelSessionCmd")] CmdSyncWorldLevelSessionCmd = 40476,
    [pbr::OriginalName("CMD_SendLuaErrorInfoSessionCmd")] CmdSendLuaErrorInfoSessionCmd = 40479,
    [pbr::OriginalName("CMD_RPCScriptCallCmd")] CmdRpcscriptCallCmd = 40480,
    /// <summary>
    ///  SceneServer配置热更新
    /// </summary>
    [pbr::OriginalName("CMD_SceneServerConfigReloadCmd")] CmdSceneServerConfigReloadCmd = 40482,
    [pbr::OriginalName("CMD_UserReconnectSessionCmd")] CmdUserReconnectSessionCmd = 40483,
    /// <summary>
    ///  set new char map id
    /// </summary>
    [pbr::OriginalName("CMD_SetNewCharMapSessionCmd")] CmdSetNewCharMapSessionCmd = 40484,
    [pbr::OriginalName("CMD_ForwardSceneServerCmd")] CmdForwardSceneServerCmd = 40485,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SESSION_END")] CmdSessionEnd = 40599,
    /// <summary>
    ///  GMTOOLS_PROTOCMD
    ///  40600~40799
    /// </summary>
    [pbr::OriginalName("CMD_GMTOOLS_START")] CmdGmtoolsStart = 40600,
    [pbr::OriginalName("CMD_ExecGMCmd")] CmdExecGmcmd = 40601,
    [pbr::OriginalName("CMD_RetExecGMCmd")] CmdRetExecGmcmd = 40602,
    [pbr::OriginalName("CMD_SessionGMCmd")] CmdSessionGmcmd = 40603,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_GMTOOLS_END")] CmdGmtoolsEnd = 40799,
    /// <summary>
    ///  LOG_PROTOCMD
    ///  40800~40999
    /// </summary>
    [pbr::OriginalName("CMD_LOG_START")] CmdLogStart = 40800,
    [pbr::OriginalName("CMD_LoginLogCmd")] CmdLoginLogCmd = 40801,
    [pbr::OriginalName("CMD_AccountLogCmd")] CmdAccountLogCmd = 40802,
    [pbr::OriginalName("CMD_CreateLogCmd")] CmdCreateLogCmd = 40803,
    [pbr::OriginalName("CMD_ChangeFlagLogCmd")] CmdChangeFlagLogCmd = 40804,
    [pbr::OriginalName("CMD_ChargeLogCmd")] CmdChargeLogCmd = 40805,
    [pbr::OriginalName("CMD_EventLogCmd")] CmdEventLogCmd = 40806,
    [pbr::OriginalName("CMD_IncomeLogCmd")] CmdIncomeLogCmd = 40807,
    [pbr::OriginalName("CMD_ConsumeLogCmd")] CmdConsumeLogCmd = 40808,
    [pbr::OriginalName("CMD_ItemLogCmd")] CmdItemLogCmd = 40809,
    [pbr::OriginalName("CMD_PropsLogCmd")] CmdPropsLogCmd = 40810,
    [pbr::OriginalName("CMD_TransactionLogCmd")] CmdTransactionLogCmd = 40811,
    [pbr::OriginalName("CMD_ChatLogCmd")] CmdChatLogCmd = 40812,
    [pbr::OriginalName("CMD_LevelLogCmd")] CmdLevelLogCmd = 40813,
    [pbr::OriginalName("CMD_OnlineLogCmd")] CmdOnlineLogCmd = 40814,
    [pbr::OriginalName("CMD_CheckpointLogCmd")] CmdCheckpointLogCmd = 40815,
    [pbr::OriginalName("CMD_RankLogCmd")] CmdRankLogCmd = 40816,
    [pbr::OriginalName("CMD_ChangeLogCmd")] CmdChangeLogCmd = 40818,
    [pbr::OriginalName("CMD_EquipLogCmd")] CmdEquipLogCmd = 40819,
    [pbr::OriginalName("CMD_CardLogCmd")] CmdCardLogCmd = 40820,
    [pbr::OriginalName("CMD_EquipUpLogCmd")] CmdEquipUpLogCmd = 40821,
    [pbr::OriginalName("CMD_SocailLogCmd")] CmdSocailLogCmd = 40822,
    [pbr::OriginalName("CMD_QuestLogCmd")] CmdQuestLogCmd = 40823,
    [pbr::OriginalName("CMD_ManualLogCmd")] CmdManualLogCmd = 40824,
    [pbr::OriginalName("CMD_CompleteLogCmd")] CmdCompleteLogCmd = 40825,
    [pbr::OriginalName("CMD_ItemOperLogCmd")] CmdItemOperLogCmd = 40827,
    [pbr::OriginalName("CMD_KillLogCmd")] CmdKillLogCmd = 40828,
    [pbr::OriginalName("CMD_RewardLogCmd")] CmdRewardLogCmd = 40829,
    [pbr::OriginalName("CMD_MailLogCmd")] CmdMailLogCmd = 40830,
    [pbr::OriginalName("CMD_DojoLogCmd")] CmdDojoLogCmd = 40831,
    [pbr::OriginalName("CMD_EnchantLogCmd")] CmdEnchantLogCmd = 40832,
    [pbr::OriginalName("CMD_GuildPrayLogCmd")] CmdGuildPrayLogCmd = 40833,
    [pbr::OriginalName("CMD_UseSkillLogCmd")] CmdUseSkillLogCmd = 40834,
    [pbr::OriginalName("CMD_ActiveLogCmd")] CmdActiveLogCmd = 40835,
    [pbr::OriginalName("CMD_TradeLogCmd")] CmdTradeLogCmd = 40836,
    [pbr::OriginalName("CMD_DeleteCharLogCmd")] CmdDeleteCharLogCmd = 40837,
    [pbr::OriginalName("CMD_ComposeLogCmd")] CmdComposeLogCmd = 40838,
    [pbr::OriginalName("CMD_JumpzoneLogCmd")] CmdJumpzoneLogCmd = 40839,
    [pbr::OriginalName("CMD_TeamLogCmd")] CmdTeamLogCmd = 40840,
    [pbr::OriginalName("CMD_TradeAdjustPriceLogCmd")] CmdTradeAdjustPriceLogCmd = 40841,
    [pbr::OriginalName("CMD_TradePriceLogCmd")] CmdTradePriceLogCmd = 40842,
    [pbr::OriginalName("CMD_TradeUntakeLogCmd")] CmdTradeUntakeLogCmd = 40845,
    [pbr::OriginalName("CMD_InactiveUserLogCmd")] CmdInactiveUserLogCmd = 40846,
    [pbr::OriginalName("CMD_CreditLogCmd")] CmdCreditLogCmd = 40847,
    [pbr::OriginalName("CMD_TradeGiveLogCmd")] CmdTradeGiveLogCmd = 40848,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_LOG_END")] CmdLogEnd = 40999,
    /// <summary>
    ///  GATE_SUPER_PROTOCMD
    ///  41000~41199
    /// </summary>
    [pbr::OriginalName("CMD_GATE_SUPER_START")] CmdGateSuperStart = 41000,
    [pbr::OriginalName("CMD_GateToSuperUserNum")] CmdGateToSuperUserNum = 41001,
    [pbr::OriginalName("CMD_PushMsgGateSuperCmd")] CmdPushMsgGateSuperCmd = 41002,
    [pbr::OriginalName("CMD_AlterMsgGateSuperCmd")] CmdAlterMsgGateSuperCmd = 41003,
    [pbr::OriginalName("CMD_PushTyrantDbGateSuperCmd")] CmdPushTyrantDbGateSuperCmd = 41004,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_GATE_SUPER_END")] CmdGateSuperEnd = 41199,
    /// <summary>
    ///  STAT_PROTOCMD
    ///  41400~41599
    /// </summary>
    [pbr::OriginalName("CMD_STAT_START")] CmdStatStart = 41400,
    [pbr::OriginalName("CMD_TestStatCmd")] CmdTestStatCmd = 41401,
    [pbr::OriginalName("CMD_StatCmd")] CmdStatCmd = 41402,
    [pbr::OriginalName("CMD_TradeToStatLogCmd")] CmdTradeToStatLogCmd = 41403,
    [pbr::OriginalName("CMD_KillMonsterNumStatCmd")] CmdKillMonsterNumStatCmd = 41404,
    [pbr::OriginalName("CMD_DayGetZenyCountCmd")] CmdDayGetZenyCountCmd = 41405,
    [pbr::OriginalName("CMD_StatCurLevel")] CmdStatCurLevel = 41406,
    [pbr::OriginalName("CMD_ReqWorldLevelCmd")] CmdReqWorldLevelCmd = 41407,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_STAT_END")] CmdStatEnd = 41599,
    /// <summary>
    ///  MATCHS_PROTOCMD
    ///  42400~42599
    /// </summary>
    [pbr::OriginalName("CMD_MATCHS_START")] CmdMatchsStart = 42400,
    /// <summary>
    ///  玩家报名
    /// </summary>
    [pbr::OriginalName("CMD_MatchPlayJoinCmd")] CmdMatchPlayJoinCmd = 42401,
    /// <summary>
    ///  玩家离开
    /// </summary>
    [pbr::OriginalName("CMD_MatchPlayLeaveCmd")] CmdMatchPlayLeaveCmd = 42402,
    /// <summary>
    ///  回复报名结果
    /// </summary>
    [pbr::OriginalName("CMD_RetMatchPlayJoinCmd")] CmdRetMatchPlayJoinCmd = 42403,
    /// <summary>
    ///  回复退出结果
    /// </summary>
    [pbr::OriginalName("CMD_RetMatchPlayLeaveCmd")] CmdRetMatchPlayLeaveCmd = 42404,
    /// <summary>
    ///  通知场景服匹配成功
    /// </summary>
    [pbr::OriginalName("CMD_MatchSuccessCmd")] CmdMatchSuccessCmd = 42405,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_MATCHS_END")] CmdMatchsEnd = 42599,
    /// <summary>
    ///  GATEWAY_CMD
    ///  43200~43399
    /// </summary>
    [pbr::OriginalName("CMD_GATEWAY_START")] CmdGatewayStart = 43200,
    [pbr::OriginalName("CMD_UserDataGatewayCmd")] CmdUserDataGatewayCmd = 43201,
    [pbr::OriginalName("CMD_ForwardUserCmdGatewayCmd")] CmdForwardUserCmdGatewayCmd = 43202,
    [pbr::OriginalName("CMD_ForwardToUserGatewayCmd")] CmdForwardToUserGatewayCmd = 43203,
    [pbr::OriginalName("CMD_ForwardToLoginUserGatewayCmd")] CmdForwardToLoginUserGatewayCmd = 43204,
    [pbr::OriginalName("CMD_BroadcastOneLevelIndexGatewayCmd")] CmdBroadcastOneLevelIndexGatewayCmd = 43206,
    [pbr::OriginalName("CMD_AddOneLevelIndexGatewayCmd")] CmdAddOneLevelIndexGatewayCmd = 43207,
    [pbr::OriginalName("CMD_DelOneLevelIndexGatewayCmd")] CmdDelOneLevelIndexGatewayCmd = 43208,
    [pbr::OriginalName("CMD_CmdFilterGatewayCmd")] CmdCmdFilterGatewayCmd = 43209,
    [pbr::OriginalName("CMD_LoginGateCmd")] CmdLoginGateCmd = 43210,
    [pbr::OriginalName("CMD_LogoutGateCmd")] CmdLogoutGateCmd = 43211,
    [pbr::OriginalName("CMD_LogoutRegGateCmd")] CmdLogoutRegGateCmd = 43212,
    [pbr::OriginalName("CMD_CreateCharGateCmd")] CmdCreateCharGateCmd = 43213,
    [pbr::OriginalName("CMD_RetCreateCharGateCmd")] CmdRetCreateCharGateCmd = 43214,
    [pbr::OriginalName("CMD_DelCharGateCmd")] CmdDelCharGateCmd = 43216,
    [pbr::OriginalName("CMD_RetDelCharGateCmd")] CmdRetDelCharGateCmd = 43217,
    [pbr::OriginalName("CMD_UserRenameGateCmd")] CmdUserRenameGateCmd = 43218,
    [pbr::OriginalName("CMD_GateUserOnlineGatewayCmd")] CmdGateUserOnlineGatewayCmd = 43219,
    [pbr::OriginalName("CMD_RefreshSnapshotClientUserCmd")] CmdRefreshSnapshotClientUserCmd = 43220,
    [pbr::OriginalName("CMD_DisconnectClientUserCmd")] CmdDisconnectClientUserCmd = 43222,
    [pbr::OriginalName("CMD_ReqSnapshotGateCmd")] CmdReqSnapshotGateCmd = 43223,
    [pbr::OriginalName("CMD_RetSnapshotGateCmd")] CmdRetSnapshotGateCmd = 43224,
    [pbr::OriginalName("CMD_ReloginDisconnectGateCmd")] CmdReloginDisconnectGateCmd = 43225,
    [pbr::OriginalName("CMD_ReloginKickUserGateCmd")] CmdReloginKickUserGateCmd = 43226,
    [pbr::OriginalName("CMD_LoginErrorGateCmd")] CmdLoginErrorGateCmd = 43227,
    /// <summary>
    ///  Scene服->Gate服 更新该Scene服计数
    /// </summary>
    [pbr::OriginalName("CMD_SceneUserCountCmd")] CmdSceneUserCountCmd = 43228,
    [pbr::OriginalName("CMD_ChangeSceneServerCmd")] CmdChangeSceneServerCmd = 43229,
    [pbr::OriginalName("CMD_ConnectionCloseGateCmd")] CmdConnectionCloseGateCmd = 43230,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_GATEWAY_END")] CmdGatewayEnd = 43399,
    /// <summary>
    ///  SYSTEM_PROTOCMD
    ///  43600~43799
    /// </summary>
    [pbr::OriginalName("CMD_SYSTEM_START")] CmdSystemStart = 43600,
    [pbr::OriginalName("CMD_VerifyConnSystemCmd")] CmdVerifyConnSystemCmd = 43602,
    [pbr::OriginalName("CMD_ServerTimeSystemCmd")] CmdServerTimeSystemCmd = 43605,
    [pbr::OriginalName("CMD_CommonReloadSystemCmd")] CmdCommonReloadSystemCmd = 43607,
    [pbr::OriginalName("CMD_ReloadLogConfigCmd")] CmdReloadLogConfigCmd = 43608,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_SYSTEM_END")] CmdSystemEnd = 43799,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_GATEWAY_CHAT_START")] CmdGatewayChatStart = 43800,
    /// <summary>
    ///  Gate转发聊天到ChatServer
    /// </summary>
    [pbr::OriginalName("CMD_GateToChatServerCmd")] CmdGateToChatServerCmd = 43801,
    /// <summary>
    ///  Gate接收ChatServer的消息
    /// </summary>
    [pbr::OriginalName("CMD_ChatServerToGateCmd")] CmdChatServerToGateCmd = 43802,
    /// <summary>
    ///  接收ChatServer的错误信息
    /// </summary>
    [pbr::OriginalName("CMD_ChatServerErrorCmd")] CmdChatServerErrorCmd = 43805,
    /// <summary>
    ///  不要使用，作为标志用
    /// </summary>
    [pbr::OriginalName("CMD_GATEWAY_CHAT_END")] CmdGatewayChatEnd = 43999,
    /// <summary>
    ///  MAX
    /// </summary>
    [pbr::OriginalName("CMD_MAX")] CmdMax = 65535,
  }

  #endregion

  #region Messages
  public sealed partial class Nonce : pb::IMessage<Nonce> {
    private static readonly pb::MessageParser<Nonce> _parser = new pb::MessageParser<Nonce>(() => new Nonce());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Nonce> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cmd.XCmdReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Nonce() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Nonce(Nonce other) : this() {
      timestamp_ = other.timestamp_;
      index_ = other.index_;
      sign_ = other.sign_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Nonce Clone() {
      return new Nonce(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private uint timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 2;
    private uint index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "sign" field.</summary>
    public const int SignFieldNumber = 3;
    private string sign_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sign {
      get { return sign_; }
      set {
        sign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Nonce);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Nonce other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if (Index != other.Index) return false;
      if (Sign != other.Sign) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
      if (Index != 0) hash ^= Index.GetHashCode();
      if (Sign.Length != 0) hash ^= Sign.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Timestamp);
      }
      if (Index != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Index);
      }
      if (Sign.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Sign);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Timestamp);
      }
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Index);
      }
      if (Sign.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sign);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Nonce other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0) {
        Timestamp = other.Timestamp;
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      if (other.Sign.Length != 0) {
        Sign = other.Sign;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Timestamp = input.ReadUInt32();
            break;
          }
          case 16: {
            Index = input.ReadUInt32();
            break;
          }
          case 26: {
            Sign = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class WrapPacket : pb::IMessage<WrapPacket> {
    private static readonly pb::MessageParser<WrapPacket> _parser = new pb::MessageParser<WrapPacket>(() => new WrapPacket());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WrapPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cmd.XCmdReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WrapPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WrapPacket(WrapPacket other) : this() {
      cmd_ = other.cmd_;
      content_ = other.content_;
      timestamp_ = other.timestamp_;
      seq_ = other.seq_;
      code_ = other.code_;
      reconnectreq_ = other.reconnectreq_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WrapPacket Clone() {
      return new WrapPacket(this);
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 1;
    private global::Cmd.CommandList cmd_ = 0;
    /// <summary>
    ///  协议编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Cmd.CommandList Cmd {
      get { return cmd_; }
      set {
        cmd_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 2;
    private pb::ByteString content_ = pb::ByteString.Empty;
    /// <summary>
    ///  协议二进制
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private ulong timestamp_;
    /// <summary>
    ///  时间戳(只会增大)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "seq" field.</summary>
    public const int SeqFieldNumber = 4;
    private uint seq_;
    /// <summary>
    ///  序列号(只会增大)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 5;
    private uint code_;
    /// <summary>
    ///  错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "reconnectreq" field.</summary>
    public const int ReconnectreqFieldNumber = 6;
    private uint reconnectreq_;
    /// <summary>
    /// 重连序列号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Reconnectreq {
      get { return reconnectreq_; }
      set {
        reconnectreq_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WrapPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WrapPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cmd != other.Cmd) return false;
      if (Content != other.Content) return false;
      if (Timestamp != other.Timestamp) return false;
      if (Seq != other.Seq) return false;
      if (Code != other.Code) return false;
      if (Reconnectreq != other.Reconnectreq) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cmd != 0) hash ^= Cmd.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (Seq != 0) hash ^= Seq.GetHashCode();
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Reconnectreq != 0) hash ^= Reconnectreq.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Cmd != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Cmd);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Content);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Timestamp);
      }
      if (Seq != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Seq);
      }
      if (Code != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Code);
      }
      if (Reconnectreq != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Reconnectreq);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cmd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Cmd);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Content);
      }
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (Seq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Seq);
      }
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Code);
      }
      if (Reconnectreq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Reconnectreq);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WrapPacket other) {
      if (other == null) {
        return;
      }
      if (other.Cmd != 0) {
        Cmd = other.Cmd;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.Seq != 0) {
        Seq = other.Seq;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Reconnectreq != 0) {
        Reconnectreq = other.Reconnectreq;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            cmd_ = (global::Cmd.CommandList) input.ReadEnum();
            break;
          }
          case 18: {
            Content = input.ReadBytes();
            break;
          }
          case 24: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 32: {
            Seq = input.ReadUInt32();
            break;
          }
          case 40: {
            Code = input.ReadUInt32();
            break;
          }
          case 48: {
            Reconnectreq = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
