//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Client_Data_LevelTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Client.Data.LevelType));
		L.RegVar("Init", new LuaCSFunction(get_Init), null);
		L.RegVar("Login", new LuaCSFunction(get_Login), null);
		L.RegVar("Loader", new LuaCSFunction(get_Loader), null);
		L.RegVar("Main", new LuaCSFunction(get_Main), null);
		L.RegVar("Battle", new LuaCSFunction(get_Battle), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<Client.Data.LevelType>.Check = CheckType;
		StackTraits<Client.Data.LevelType>.Push = Push;
	}

	static void Push(IntPtr L, Client.Data.LevelType arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_Client_Data_LevelType = typeof(Client.Data.LevelType);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_Client_Data_LevelType, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Init(IntPtr L)
	{
		ToLua.Push(L, Client.Data.LevelType.Init);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Login(IntPtr L)
	{
		ToLua.Push(L, Client.Data.LevelType.Login);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Loader(IntPtr L)
	{
		ToLua.Push(L, Client.Data.LevelType.Loader);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Main(IntPtr L)
	{
		ToLua.Push(L, Client.Data.LevelType.Main);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Battle(IntPtr L)
	{
		ToLua.Push(L, Client.Data.LevelType.Battle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		Client.Data.LevelType o = (Client.Data.LevelType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

