//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Client_Manager_NetworkManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Client.Manager.NetworkManager), typeof(Client.Manager.BaseManager));
		L.RegFunction("Connect", new LuaCSFunction(Connect));
		L.RegFunction("SendData", new LuaCSFunction(SendData));
		L.RegFunction("New", new LuaCSFunction(_CreateClient_Manager_NetworkManager));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("mClient", new LuaCSFunction(get_mClient), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateClient_Manager_NetworkManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Client.Manager.NetworkManager obj = new Client.Manager.NetworkManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Client.Manager.NetworkManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Connect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			Client.Manager.NetworkManager obj = (Client.Manager.NetworkManager)ToLua.CheckObject<Client.Manager.NetworkManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checkinteger(L, 3);
			LuaTable arg2 = ToLua.CheckLuaTable(L, 4);
			LuaFunction arg3 = ToLua.CheckLuaFunction(L, 5);
			LuaFunction arg4 = ToLua.CheckLuaFunction(L, 6);
			obj.Connect(arg0, arg1, arg2, arg3, arg4);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes<Google.Protobuf.IMessage>(L, 3))
			{
				Client.Manager.NetworkManager obj = (Client.Manager.NetworkManager)ToLua.CheckObject<Client.Manager.NetworkManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				Google.Protobuf.IMessage arg1 = (Google.Protobuf.IMessage)ToLua.ToObject(L, 3);
				obj.SendData(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<LuaInterface.LuaByteBuffer>(L, 3))
			{
				Client.Manager.NetworkManager obj = (Client.Manager.NetworkManager)ToLua.CheckObject<Client.Manager.NetworkManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				LuaByteBuffer arg1 = new LuaByteBuffer(ToLua.CheckByteBuffer(L, 3));
				obj.SendData(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Client.Manager.NetworkManager.SendData");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mClient(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Client.Manager.NetworkManager obj = (Client.Manager.NetworkManager)o;
			LiteNetLib.NetManager ret = obj.mClient;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mClient on a nil value");
		}
	}
}

