//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FirClient_Component_FollowTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(Client.Component.FollowType));
		L.RegVar("ObjectFollowCamera", new LuaCSFunction(get_ObjectFollowCamera), null);
		L.RegVar("CameraFollowRole", new LuaCSFunction(get_CameraFollowRole), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<Client.Component.FollowType>.Check = CheckType;
		StackTraits<Client.Component.FollowType>.Push = Push;
	}

	static void Push(IntPtr L, Client.Component.FollowType arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_FirClient_Component_FollowType = typeof(Client.Component.FollowType);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_FirClient_Component_FollowType, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ObjectFollowCamera(IntPtr L)
	{
		ToLua.Push(L, Client.Component.FollowType.ObjectFollowCamera);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraFollowRole(IntPtr L)
	{
		ToLua.Push(L, Client.Component.FollowType.CameraFollowRole);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		Client.Component.FollowType o = (Client.Component.FollowType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

